### ISSUE TITLE
Can't block Youtube

### ISSUE THREAD

**Issue by yoshi4205** [SelfControlApp/selfcontrol#131]
I have been able to block EVERY site using self control EXCEPT youtube.  I have tried entering www.youtube.com, new.youtube.com EVERYTHING, I even cleared all my internet history.  Anyone have any ideas?

**Comment by hwikle** [comment]
I think this issue is incorrectly marked as closed. I'm still having the same problem. Can it be re-opened?

**Comment by pentallelogram** [comment]
I fixed this issue for me in firefox by disabling DNS over HTTPS:

1. Firefox > Preferences > Network Settings > uncheck Enable DNS over HTTPS
2. Restart Firefox

This may be relevant for other browsers as well, just search "DNS over HTTPS" in settings. Keep in mind that DNS over HTTPS is a feature that helps protect your privacy but it does so by bypassing the host system DNS, therefore breaking SelfControl.

https://support.mozilla.org/en-US/kb/firefox-dns-over-https

**Comment by Crystal-cxyz** [comment]
It works for me on Chrome, but not on firefox.
