### ISSUE TITLE
blocking gmail does not work

### ISSUE THREAD

**Issue by Januzz** [SelfControlApp/selfcontrol#134]
As I wrote in this issue https://github.com/slambert/selfcontrol/issues/133, I seem not to be able to block gmail.

I added the following entry to the blacklist:

imap.googlemail.com:993

However, mails are still coming through. What am I doing wrong? What are your settings when you want to block gmail?

Thanks!

**Comment by slambert** [comment]
Maybe this will help determine the URL to block it:

http://radiosilenceapp.com/private-eye
