### ISSUE TITLE
I find it's too easy to disable selfcontrol by just changing the date. Anyway around this?

### ISSUE THREAD

**Issue by ghost** [SelfControlApp/selfcontrol#146]
As an avid procrastinator, I liked selfcontrol because it gave me no options of going around it unless I really started to poke around. 
Then I found I can just change the date. This takes literately 2 seconds and kind of ruined the whole thing for me.

Is there anything I can do to remedy this?

**Comment by valimikayilov** [comment]
> After getting more familiar with SelfControl I learned that you can break its lock by either changing the time or using the terminal to edit the hosts files.
> 
> The only way to completely disable yourself from breaking the Selfcontrol lock is by taking away admin privileges away from yourself. This is a drastic solution but unfortunately at times necessary.
> 
> I made a new user account and renamed it admin, then I set the password to a random bunch of letters. I sent this random bunch of letters to myself through one of the many future email websites. After a specified date I receive the password and only then can I unlock SelfControl. Until then, I can't change the host files or change the time.
> 
> Like I said, this is a drastic solution, but until I or someone else finds a more elegant solution, this will have to do.

I think a better solution would be instead of sending it via email, if you can write to some online note taking website and then block the website with the selfcontrol.app
