### ISSUE TITLE
Block wildcard subdomain

### ISSUE THREAD

**Issue by anedisi** [SelfControlApp/selfcontrol#185]
How to bock all subdomains of domain ?
I have tried with *.domain.com or with .domain.com and it did not work ?

blocking reddit.com does not block any of bl.reddit.com gg.reddit.com and so on.

Also great App and thank you.

**Comment by pablomarti** [comment]
Hi! is there any change with this? how can I help to add something to block domains? Will try to see the code tomorrow and make a fork, any suggestion?

**Comment by cstigler** [comment]
Hi @pablomarti thanks for offering to help! Unfortunately, I think this would require essentially replacing the entire blocking engine, probably with a proxy-based solution (i.e. all requests go through a local proxy server, which can inspect the URL before returning the page). I don't believe this is possible using the `/etc/hosts` file or `pf` firewall, which are the two blocking methods we currently use. I hope I'm wrong! Please post back if you get a fork working =)
