### ISSUE TITLE
SelfControl 2.0.2 keeps on crashing on start

### ISSUE THREAD

**Issue by citrikwave** [SelfControlApp/selfcontrol#246]
Hey there,

I downloaded the 2.0.2 version recently, and it crashed right away. Couldn't even see the app. It reminded me that I uninstalled the app because of the same problem back then.
Can someone help me with this ? Thank you in advance !

Mac osx 10.9.5
2,5GHz i5
4Go

**Comment by slambert** [comment]
Assuming this is resolved.
