### ISSUE TITLE
Focus on start button when the application starts

### ISSUE THREAD

**Issue by godbout** [SelfControlApp/selfcontrol#247]
Hi. Wouldn't it be nice if the start button was focused when the application opens?

I open SelfControl with Alfred but I always have to move the mouse in order to start the countdown. I'd like to open, click enter, enter the password and go!

**Comment by godbout** [comment]
@slambert @cstigler just to let you know, I've made a pull request with that change. Tested and it works. Made the change for every language window.

**Comment by slambert** [comment]
Thank you!

**Comment by cstigler** [comment]
Merged thank you!
