### ISSUE TITLE
Self Control is now blocking my Media server.  Any guru help me out.  Im not good at this stuff

### ISSUE THREAD

**Issue by kolakube** [SelfControlApp/selfcontrol#267]
Hey guys,

I have a media server connected to my broadband router thingy (UK speak) and every time I block my sites it also blocks access to that too.  

Is there any way to allow access?  I was thinking maybe I need to white list a port number?  I have little clue to what I just said.  Anyone please be kind enough to talk me through.  

Warm regards

Michael

**Comment by kolakube** [comment]
ANyone?

**Comment by cstigler** [comment]
@kolakube it will differ depending on how your media server works, and the type of block you're running. If it's a whitelist block, you'll need to make sure your media server is whitelisted. You can whitelist it by IP address or using the port number it runs on. See FAQ for info on port blocking: https://github.com/SelfControlApp/selfcontrol/wiki/FAQ

**Comment by kolakube** [comment]
Hi mate,   thanks but that doesn't help.  

Here is my NAS IP.

![screen shot 2015-02-27 at 21 44 37](https://cloud.githubusercontent.com/assets/4777600/6421806/43845e1a-beca-11e4-86c5-391b13a20b6c.png)

And here is the IP I have whitelisted.  

![screen shot 2015-02-27 at 21 43 54](https://cloud.githubusercontent.com/assets/4777600/6421820/5e02b0e8-beca-11e4-99d4-174f93796750.png)


Nothing doing.  Anything else I could have wrong?

**Comment by cstigler** [comment]
@kolakube that looks about right. I couldn't say for sure why it isn't working. It's possible that connecting to the NAS server requires communication with another IP address. You could try something like [Private Eye](http://radiosilenceapp.com/private-eye) to see what connections are use. Good luck making it work!
