### ISSUE TITLE
Error when trying to start Self Control from command line

### ISSUE THREAD

**Issue by firvorski** [SelfControlApp/selfcontrol#276]
`sudo  /Applications/SelfControl.app/Contents/MacOS/org.eyebeam.SelfControl $(id -u $(whoami)) --install`

I tried to run this command but it won't start and it gives me the following error:

`2015-03-19 18:02:32.886 org.eyebeam.SelfControl[31556:738585] Using your own bundle identifier as an NSUserDefaults suite name does not make sense and will not work. Break on _NSUserDefaults_Log_Nonsensical_Suites to find this
2015-03-19 18:02:32.912 org.eyebeam.SelfControl[31556:738585] ERROR: Not enough block information.`

`defaults read org.eyebeam.SelfControl` shows that the variables are set

`BlockAsWhitelist = 0;
    BlockDuration = 15;
    GetStartedShown = 1;
    HostBlacklist =     (
        "reddit.com",
        "bbc.co.uk",
        "guardian.co.uk",
        "independent.co.uk",...`

**Comment by stephjang** [comment]
Bump. Getting the same error here.

```
$ sudo /Applications/SelfControl.app/Contents/MacOS/org.eyebeam.SelfControl $(id -u $(whoami)) --install
2015-04-18 14:24:36.803 org.eyebeam.SelfControl[51016:6272117] Using your own bundle identifier as an NSUserDefaults suite name does not make sense and will not work. Break on _NSUserDefaults_Log_Nonsensical_Suites to find this
2015-04-18 14:24:36.819 org.eyebeam.SelfControl[51016:6272117] ERROR: Not enough block information.
-210
```

I made sure to set `BlockDuration`, `HostBlacklist`, and  `BlockAsWhitelist`, as described in [the wiki article](https://github.com/SelfControlApp/selfcontrol/wiki/Running-SelfControl-from-the-Terminal). My settings are below:

```
$ defaults read org.eyebeam.SelfControl
{
    BlockAsWhitelist = 1;
    BlockDuration = 1;
    BlockLengthInterval = 1;
    BlockSound = 12;
    BlockSoundShouldPlay = 1;
    BlockStartedDate = "4001-01-01 00:00:00 +0000";
    GetStartedShown = 1;
    HostBlacklist =     (
        "calendar.google.com",
        "docs.google.com",
        "drive.google.com",
        "beeminder.com",
        "trello.com",
        "grooveshark.com",
        "songza.com",
        "pomotodo.com",
        "todoist.com",
        "quip.com"
    );
    "MASPreferences Frame Top Left" = "{758, 725}";
    "MASPreferences GeneralPreferences Frame" = "{{0, 0}, {1440, 796}}";
    "MASPreferences Selected Identifier View" = AdvancedPreferences;
    MaxBlockLength = 3;
    NSNavLastRootDirectory = "~/Documents";
    SULastCheckTime = "2015-04-18 21:23:41 +0000";
}
```

**Comment by andreasgrill** [comment]
Have a look at https://github.com/SelfControlApp/selfcontrol/issues/284.

**Comment by cstigler** [comment]
Thanks @andreasgrill ! I believe if y'all pull from master now that his changes are in, rebuild, and try this again, it should work. Somebody reopen if there are still issues!
