### ISSUE TITLE
can still access cites by pressing "back"

### ISSUE THREAD

**Issue by rebeccaherman1** [SelfControlApp/selfcontrol#279]
All I need to do is type the cite, then go to another cite, and then press "back"

**Comment by slambert** [comment]
SelfControl doesn't delete your cache. If you refresh that page after hitting "back" it wont load. 

Though I wonder how possible it would be to delete the cache in common browsers? I know there's a command in Onyx that does it, so it's possible within an application...

**Comment by rebeccaherman1** [comment]
thanks :)
