### ISSUE TITLE
start from command line...

### ISSUE THREAD

**Issue by thleonardo** [SelfControlApp/selfcontrol#284]
As others had reported before, there are errors when trying to start selfcontrol from the command line. 

I tried to find the problem by downloading the source code...

1) If the defaults do not specify a BlockStartedDate (as proposed...) I get the error

 ERROR: Not enough block information.

It turns out to be at the place in the source code

[lockDictionary[@"BlockStartedDate"] isEqualToDate: [NSDate distantFuture]

... so the BlockStartedDate is set to "distantFuture" by default... and stops the operation for being "distantFuture".

2) If I do specify something for BlockStartedDate (e. g., some date value formatted in the same way as the software writes it to the defaults), then it crashes due to some problem with the "isEqualToDate" method when it first tries to compare the two dates...

So... was anyone successful to start SelfControl from the command line?

Thomas

**Comment by thleonardo** [comment]
... So I made a small change in HelperCommon.m and changed

	NSDictionary* appDefaults = @{@"BlockDuration": @15,
								  @"BlockStartedDate": [NSDate distantfuture],
								  ...


to
	NSDictionary* appDefaults = @{@"BlockDuration": @15,
								  @"BlockStartedDate": [NSDate date],
								  ...

and now it works! I can run SelfControl from the command line. The only downside is that I have to run it from my own compiled version, so this is not a solution for others using the "standard" SelfControl version.

Thomas

**Comment by noamross** [comment]
@thleonardo Can you submit this change as a pull request?

**Comment by andreasgrill** [comment]
The proposed change from thleonardo doesn't work for me as the default value will be reset after current block is finished.
However, it seems to work when you change the place where the defaults are retrieved in HelperCommon.m:
```
NSDictionary* lockDictionary = @{@"HostBlacklist": defaults[@"HostBlacklist"],
											 @"BlockDuration": defaults[@"BlockDuration"],
											 @"BlockStartedDate": [NSDate date],
...
```

**Comment by andreasgrill** [comment]
I've created a small utility that lets you schedule and automatically start/stop SelfControl: https://github.com/andreasgrill/auto-selfcontrol

**Comment by cstigler** [comment]
Seems to be fixed now thanks to @andreasgrill !

**Comment by Kparikh9** [comment]
Hey. I'm still receiving the error when trying to execute SelfControl in the terminal: _Using your own bundle identifier as an_ _NSUserDefaults suite name does not make sense and will not work. Break on_ _NSUserDefaults_Log_Nonsensical_Suites to find this..._ I downloaded SelfControl sometime in 2016, so does the issue still lie in HelperCommon.m or somewhere else?
