### ISSUE TITLE
Sites now permanently blocked?

### ISSUE THREAD

**Issue by supercanadian** [SelfControlApp/selfcontrol#289]
So this is a little complicated.

Ran a block a couple of days ago to get some work done. Block ended. Resumed normal internet use. Hooray.

Today, I restarted my Mac and noticed that I can't access any of the sites that were blocked on my last Self Control use. I tried running a short block with the same blacklist, but it didn't change anything.

I was already using 2.0.2, so I figured I could delete the app and then redownload and try again. Except the download doesn't work now (I suspect because Self Control somehow server-blocked its own download).

Then tried the terminal fix. Except /etc/hosts/.bak no longer exists, and there aren't any blocked sites in /etc/hosts (I tried a manual inspect with sudo nano and found nothing out of the ordinary).

So now I'm stuck with no app, no /etc/hosts anomalies to delete, and no access to the sites that I was using last night. Any tips would be greatly appreciated.

**Comment by musefreak14** [comment]
Friend is having the exact same issue, seems to be a thing that just happened today.

**Comment by supercanadian** [comment]
Fixed it.

I manually retyped /etc/hosts and restarted. Must've missed something earlier.
