### ISSUE TITLE
El Capitan Beta: Timer has white bar on it

### ISSUE THREAD

**Issue by raumzeit77** [SelfControlApp/selfcontrol#290]
Running the latest osx El Capitan Beta o  late-2012 McBook Pro. Application works fine, but the background of the timer isn't only black anymore: there's an white bar at the bottom. 
Screenshot: http://imgur.com/jJEH0Kq
Guess many people who'll run El Capitan in the future weeks will encounter the same problem.

**Comment by cstigler** [comment]
Hm, weird. I don't install beta OS X versions, so if you / anybody else are able to fix/test it and submit a PR that would be great!

**Comment by blaichch** [comment]
Works fine for me on the final release of OS X 10.11 (15A284).

**Comment by raumzeit77** [comment]
for me too now. strange, but hey, I won’t complain ;)

**Comment by cstigler** [comment]
Glad to hear it's working in the final release! Somebody reopen if it breaks again
