### ISSUE TITLE
Cannot Access any websites

### ISSUE THREAD

**Issue by sreinheimer** [SelfControlApp/selfcontrol#291]
In the past SelfControl has worked as expected. Today after about a year, which included an upgrade to OS X (10.10.3) and SelfControl (2.something - the latest version which I downloaded today), I cannot access any websites while self control is running. Thankfully, I set it for 15 minutes rather than my usual 10hrs. I tried twice and got the same response. The sites that are blocked say they are blocked, but the non blocked sites just don't load. I'll provide more information if someone will help me look into this.

Thanks,

Steve

**Comment by B-Genc** [comment]
Greetings, Steve!
I'm not the author of this app, but as I am familiar with linux, I've learned how the app works.
Basically it edits your hosts file, which blocks the desired websites and network locations.
Simply do these 
1. Open Terminal
2. Type sudo nano /etc/hosts
3. Enter your password if required
4. remove the part with # BEGIN SELFCONTROL BLOCK and # END SELFCONTROL BLOCK
5. press control - X
6. press y

Maybe this won't help you after 28 days but other people who search about this may find this useful.

**Comment by sreinheimer** [comment]
I forget is OS X a linux operating system? I’m using OS X on a Mac. Regardless, although I tried it multiple times the day I entered the bug information, a week or so later miraculously it was working. I don’t argue with success.

Steve

**Comment by cstigler** [comment]
@sreinheimer glad your connection is working (did not see this ticket earlier).

@anybody who's reading: I would *not* advise following the steps posted above (by B-Genc). While it may help immediately, it will not fully remove the block and may end up making it very very very difficult to remove.

**Comment by doctariouz** [comment]
I have the linux version, blocked some websites for 1 hour. Now many days later, these websites are all blocked still. They are present in the list of active blocks. I have done the steps suggested above and removed the stuff from /etc/hosts but still it wont unblock the sites. What on earth should I do?

I have also tried to reset the time and date settings and reopen the application. Still not working.

**Comment by slambert** [comment]
Linux version isn't the same codebase, so I'm guessing everyone here 
wouldn't have the experience to help. Try contacting the developer? I 
think the linux site should lead you there.

Sorry to hear your having trouble with it.

SL
