### ISSUE TITLE
large format laser

### ISSUE THREAD

**Issue by damonbowe** [SelfControlApp/selfcontrol#293]
Do you have a laser that can etch a 40x10inch piece of plywood? I'm having trouble getting something that can handle those dimensions. I need help finding one. Found you on the lasersaur page.

Thanks,
Damon

**Comment by cstigler** [comment]
Hi there! This is a free and open-source software project that helps Mac users block their own access to distracting sites on the internet. I don't know where you can find a laser, but this isn't the proper place to look. Thanks!
