### ISSUE TITLE
"block everything"

### ISSUE THREAD

**Issue by pheonixia** [SelfControlApp/selfcontrol#296]
Is it possible to block everything, but create some whitelist websites that you are still allowed to go on?

For example, I would like to literally block everything but Moodle and some other educational platforms for specific amount of time. 

I have tried things like Leechblock before but I noticed that I would just end up wasting time on sites that I never even considered or used to go on before once my main websites for wasting time were blocked.

**Comment by slambert** [comment]
Yes. Hit `edit blacklist` and select "whitelist" instead of "blacklist".
