### ISSUE TITLE
Fancier Icon?

### ISSUE THREAD

**Issue by korve** [SelfControlApp/selfcontrol#301]
Well, the icon in the taskbar looks a little bit cheap. 
<img width="51" alt="screen shot 2015-10-22 at 17 31 14" src="https://cloud.githubusercontent.com/assets/4459994/10669818/c59c5f9c-78e2-11e5-84d2-ce66cc6d3964.png">

I would suggest a new icon. Is there anything planned? I could make something i guess.

**Comment by josephfusco** [comment]
+1 for this

**Comment by cstigler** [comment]
:)
