### ISSUE TITLE
ERROR: Not enough block information.

### ISSUE THREAD

**Issue by beboppinbobby** [SelfControlApp/selfcontrol#302]
I get the following error:

> $ sudo /Applications/SelfControl.app/Contents/MacOS/org.eyebeam.SelfControl $(id -u $(whoami)) --install
> 2015-10-29 15:50:06.592 org.eyebeam.SelfControl[37539:a07] ERROR: Not enough block information.
> -210

With the following settings:

> $ defaults read org.eyebeam.SelfControl
> {
>     BlockDuration = 5;
>     BlockLengthInterval = 1;
>     BlockSound = 12;
>     BlockStartedDate = "4001-01-01 00:00:00 +0000";
>     ClearCaches = 0;
>     GetStartedShown = 1;
>     HostBlacklist =     (
>         "list.com",
>         "of.com",
>         "websites.com"
>     );
>     "MASPreferences Selected Identifier View" = GeneralPreferences;
>     MaxBlockLength = 60;
>     NSNavLastRootDirectory = "~/Documents";
>     SULastCheckTime = "2015-10-29 09:00:01 +0000";
>     VerifyInternetConnection = 0;
> }

Any suggestions?

**Comment by andreasgrill** [comment]
Have a look at https://github.com/SelfControlApp/selfcontrol/issues/284.

**Comment by cstigler** [comment]
should be fixed in #284, please try updating to v2.1 and reopen if there are still issues
