### ISSUE TITLE
Not able to reset the timer 

### ISSUE THREAD

**Issue by tannishk** [SelfControlApp/selfcontrol#314]
I am unable to reset the timer after completion . Stuck in this manner 
![screen shot 2015-12-12 at 4 24 39 am](https://cloud.githubusercontent.com/assets/5950846/11757560/5881fe1c-a088-11e5-9496-afa93ed05e6b.png)

**Comment by slambert** [comment]
Simple question, but it has to be asked: did you press the "Stuck? Stop block manually" button?

**Comment by tannishk** [comment]
@slambert Yes i did. It goes to not responding state and i have to force quit the application . I tried to uninstall and reinstall the application but i am still facing the same issue

**Comment by cstigler** [comment]
@tannishk weird - is it still blocking websites, or is the block permanently off but you just can't restart it?

**IF the block is not active (websites are not being blocked)**, here's something to try that should reset things: quit SelfControl, open Terminal (Applications --> Utilities), type the command ```defaults delete org.eyebeam.SelfControl``` and hit enter. Then restart your computer (it's voodoo magic but it often works ;) and open SelfControl again and see if it's working.

If websites are still being blocked, or the above steps don't work, let me know and I'll see if I can help you get things sorted out.

**Comment by tannishk** [comment]
It was still blocking the sites . But then i altered the HOST file it was working after that .

**Comment by cstigler** [comment]
So it's working now? Or if not, have you tried the above steps?

**Comment by tannishk** [comment]
@cstigler its working now . I reinstalled the application again ..
