### ISSUE TITLE
Not able to block an eu. address

### ISSUE THREAD

**Issue by psaviano** [SelfControlApp/selfcontrol#317]
Hello

I've been using SelfControl for several months with great success . . .  until today.

I am trying to put a block on a url that begins https://eu.          

Even though I have added the address in the usual manner, this particular page remains unblocked and available.

Any suggestions?

**Comment by cstigler** [comment]
@psaviano there shouldn't be anything special about addresses starting with ```eu.````. I imagine it's some other property of the website, but unfortunately couldn't say for sure. You could try something like [Private Eye|http://radiosilenceapp.com/private-eye] to see where your computer is connecting to, and try blocking the site via some other method.
