### ISSUE TITLE
Whitelist enabled should be obvious

### ISSUE THREAD

**Issue by sqren** [SelfControlApp/selfcontrol#322]
When starting SelfControl, it is not obvious whether blacklist or whitelist is enabled.

As the screenshot shows, even though "Whitelist" has been selected, the text on the button still says "Edit Blacklist".

![screen shot 2016-01-10 at 15 53 27](https://cloud.githubusercontent.com/assets/209966/12222111/aa192318-b7b2-11e5-8ca2-ed182be8d50c.png)

**Comment by cstigler** [comment]
Fixed - this is very obvious in the upcoming 4.0 release (due in a few weeks)
