### ISSUE TITLE
Suggestion: Longer timeframes

### ISSUE THREAD

**Issue by tiedtiger** [SelfControlApp/selfcontrol#323]
I'd genuinely like to be able to set SC to work for durations longer than a day, maybe even without end (with some option to break that lock if needs be). Alas I'm not much for coding myself so I can but suggest it, but if you could...

**Comment by cstigler** [comment]
Good news! This already works. Check out this article to see how to do it: https://github.com/SelfControlApp/selfcontrol/wiki/Tweaking-Max-Block-Length-and-Block-Length-Interval

**Comment by ariporad** [comment]
@cstigler: I actually have a question about this: Say I block a website for 1 month. Am I going to hid some unexpected issue? (Other than not being able to access the site.)

Thanks!

**Comment by cstigler** [comment]
@ariporad nope, it should work just as well as a shorter block
