### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by Oscarteg** [SelfControlApp/selfcontrol#325]
I've added web.whatsapp.com to the block list but I can still access it when enabled.

**Comment by jakewilson801** [comment]
Is that in fact the URL that's resolved when you use the app in your browser?

**Comment by Oscarteg** [comment]
@jakewilson801 Yes it is.

**Comment by nkovshov** [comment]
Looks like Chrome has a mechanism for offline applications that saves request/response pairs, so when you don't have an Internet connection or browser can't lookup DNS, browser renders a page from this cache.
Whatsapp uses this mechanism, you can find and delete it on Developer Console -> Resources -> Cache Storage

**Comment by Alshaif** [comment]
Hi

**Comment by IngFrustrado** [comment]
Hello, Has anyone found a solution?

**Comment by valkar2701** [comment]
Its working both in safari and chrome, i tried this option as mentioned by @nkovshov. But it still seems to work. :(

**Comment by Logarythms** [comment]
It works for me if you add 'dyn.web.whatsapp.com' to the blocklist

**Comment by rdahis** [comment]
Adding 'dyn.web.whatsapp.com' to the list didn't work for me. Any other ideas?

**Comment by rdahis** [comment]
Thanks @Oscarteg, this worked for me.

**Comment by pedrokohler** [comment]
> Whatsapp uses a lot of domains so I think you have to add all the domains below to work. Not tested though.
> 
> ```
> whatsapp.com
> www.whatsapp.com
> web.whatsapp.com
> w1.web.whatsapp.com
> w2.web.whatsapp.com
> w3.web.whatsapp.com
> w4.web.whatsapp.com
> w5.web.whatsapp.com
> w6.web.whatsapp.com
> w7.web.whatsapp.com
> w8.web.whatsapp.com
> w9.web.whatsapp.com
> whatsapp-cdn-shv-01-atl1.fbcdn.net
> whatsapp-cdn-shv-01-dfw1.fbcdn.net
> whatsapp-cdn-shv-01-iad3.fbcdn.net
> whatsapp-cdn-shv-01-lax1.fbcdn.net
> whatsapp-cdn-shv-01-lax3.fbcdn.net
> whatsapp-cdn-shv-01-lga1.fbcdn.net
> whatsapp-cdn-shv-01-mia1.fbcdn.net
> whatsapp-cdn-shv-01-ord1.fbcdn.net
> whatsapp-cdn-shv-01-sea1.fbcdn.net
> whatsapp-cdn-shv-01-sjc2.fbcdn.net
> whatsapp-cdn-shv-01-arn2.fbcdn.net
> whatsapp-cdn-shv-01-bom1.fbcdn.net
> whatsapp-cdn-shv-01-cdg2.fbcdn.net
> whatsapp-cdn-shv-01-dft4.fbcdn.net
> whatsapp-cdn-shv-01-dfw5.fbcdn.net
> whatsapp-cdn-shv-01-frt3.fbcdn.net
> whatsapp-cdn-shv-01-gru2.fbcdn.net
> whatsapp-cdn-shv-01-hkg3.fbcdn.net
> whatsapp-cdn-shv-01-kut2.fbcdn.net
> whatsapp-cdn-shv-01-lhr3.fbcdn.net
> whatsapp-cdn-shv-01-mad1.fbcdn.net
> whatsapp-cdn-shv-01-sin1.fbcdn.net
> whatsapp-cdn-shv-01-sin6.fbcdn.net
> whatsapp-cdn-shv-01-sit4.fbcdn.net
> whatsapp-cdn-shv-01-vie1.fbcdn.net
> whatsapp-cdn-shv-02-sin6.fbcdn.net
> ```

This didn't work for me. It still accessible...

On the other hand, even if I search for anything related to whatsapp on google or here it blocks it. I thought it would only block things based on the base url of the page.

**Comment by mowenwi** [comment]
In my case I add web.whatsapp.com to the allow list and it makes all websites accessible.
