### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by fuzzy76** [SelfControlApp/selfcontrol#329]
The Github releases only go up to v1.5, and the Readme only lists versions up to v1.4. Where can I find out what has been changed in the releases since then?

**Comment by fuzzy76** [comment]
I guess http://selfcontrolapp.com/releasenotes.html helps somewhat, but I'd still like to see Github releases published for each version.

**Comment by chrisidefix** [comment]
I was just wondering the same thing - every release should at least be tagged in git ? Right now it's not exactly clear to me if the github repo has the latest source or if there is a gap to the v2 releases on the website?

**Comment by fuzzy76** [comment]
I'd also like to know the date of the releases...

**Comment by cstigler** [comment]
Hi all, a couple notes:

1) The GitHub repo has the latest source, always.

2) The best way to get detailed accounts of what changed per release is the commit log; the best high-level summary is the [release notes](http://selfcontrolapp.com/releasenotes.html) linked above.

3) Making a git tag for each release is a nice idea but, alas, not one I've been doing thus far.

4) While there's no pretty source for release dates, they're easy to find if you want them. For newer releases, look at the [git history for the release notes](https://github.com/SelfControlApp/selfcontrolapp.github.io/commits/master/releasenotes.html). For older releases (before the website moved to GitHub), you can still look at the [git history for Info.plist](https://github.com/SelfControlApp/selfcontrol/commits/master/Info.plist) for the version bumps.

Hope that's helpful.

**Comment by fuzzy76** [comment]
For developers yes. If you want users outside of the developer demographic, probably not.

**Comment by cstigler** [comment]
Yep - so far we've only seen this request from the dev demographic. But if you'd like to help make this kind of information more easily available to non-devs, PRs are welcome!

**Comment by fuzzy76** [comment]
That's probably because non-devs don't feel comfortable submitting issues.
