### ISSUE TITLE
Can you block google news and google images without blocking google.com search?

### ISSUE THREAD

**Issue by SarHH** [SelfControlApp/selfcontrol#330]
Hi,

The self control app is amazing and very helpful! 

Can you block google images and google news without blocking google.com search altogether on the blacklist? 

Also, do you have a mobile version of this out or in the works for iphone, that would be truly awesome as well.

Thank you!

**Comment by slambert** [comment]
I'm not sure SelfControl can really block google and not gmail. As an alternative, can I suggest https://duckduckgo.com/ for search?

For the mobile question, see our FAQ.

**Comment by SarHH** [comment]
Thank you, but I am looking to block google images and news without blocking google search. I successfully blocked gmail. But would blocking google images and news block google altogether on the blacklist? Thanks again.
