### ISSUE TITLE
iOS Content Filter

### ISSUE THREAD

**Issue by jfgonsalves** [SelfControlApp/selfcontrol#331]
Long time user of SelfControl. It's been a great help for me but could do with it on my iOS devices.

I'm not sure how flexible the iOS content filter API is, but any chance some subset of SelfControl could be ported across?

Something like this app...
https://itunes.apple.com/au/app/zero-willpower-block-distracting/id1045944416?mt=8

**Comment by cstigler** [comment]
@jfgonsalves I had the same thought. It will happen here: https://github.com/SelfControlApp/selfcontrol-mobile

(but given the amount of work involved and my current amount of free time, it probably won't happen quickly. feel free to contribute if you can!)
