### ISSUE TITLE
Update Sparkle version

### ISSUE THREAD

**Issue by xrisk** [SelfControlApp/selfcontrol#332]
https://sparkle-project.github.io/documentation/security/\#http-mitm-vulnerability

Does this affect SelfControlApp? I can see that Sparkle 1.13.0 is in use, which is vulnerable.

**Comment by cstigler** [comment]
@xrisk thanks for the concern! I was actually notified by the original reporter of this vulnerability (Radek)  prior to the public disclosure, and we resolved the issue by loading our appcast over HTTPS as of version 2.1.1. So we should be secure for now.
