### ISSUE TITLE
Build failure?

### ISSUE THREAD

**Issue by karamcnair** [SelfControlApp/selfcontrol#334]
Hi there,

I'm a developer relatively new to OSX (especially cocoapods) but with decent background in C, gcc, etc. I'm trying to build SelfControl and hitting a build issue with the MASPreferences pod. I'm running El Capitan, and I've set the build targets to 10.7 for both the core SelfControl project and the Pods project.

The build error is: 
`clang: error: -fobjc-arc is not supported on versions of OS X prior to 10.6`
 in the MASPreferences build step (I've attached the full command in a text file but it's wordy so I'm not pasting it here). Sure enough, the build command includes `-mmacosx-version-min=10.5`, which I find in the MASPreferences .podspec [here](https://github.com/CocoaPods/Specs/blob/master/Specs/MASPreferences/1.1.2/MASPreferences.podspec.json) 

What the heck am I missing? As mentioned, I'm not all that experienced with Xcode or the structure of this type of project, so I assume it's something trivial that I just don't know about - I mean, other people are building just fine, right? 

Thanks! 
[buildoutput.txt](https://github.com/SelfControlApp/selfcontrol/files/128657/buildoutput.txt)

**Comment by cstigler** [comment]
@karamcnair would love to help, but - like most Xcode issues - I have no idea why your copy is behaving differently than mine (which is building fine, as it is I think for most people). One suggestion is to try adding an explicit platform version specification at the top of the Podfile: `platform :osx, '10.7'`

If that doesn't help... I'd try making sure everything's up-to-date, clearing caches and DerivedData, and restarting your computer. I know it sounds stupid, but half of my weird Xcode issues get solved that way so ¯\_(ツ)_/¯

**Comment by karamcnair** [comment]
:smile:  Thanks! I'll give both of those a try :smile:

**Comment by karamcnair** [comment]
Found it. It's actually an issue with Ruby 2.3.x and CocoaPods (see https://github.com/CocoaPods/CocoaPods/issues/4345) Anyone who is using Ruby 2.2.x or already had their Pods installed before upgrading Ruby won't see it, but anyone starting from absolute scratch without controlling their Ruby version probably will. 

[Here's a writeup](http://karamcnair.com/2016/02/16/steps-to-build-selfcontrol-from-scratch-with-no-prior-osx-dev-experience/) on getting building from zero (I may submit a PR with a few additions to the build instructions - it's _required_ that I use the .xcworkspace file once the pods are installed, no?) I also tracked down & screencapped all the places I needed to make changes to sort out codesigning & will write that up separately - I ran out of words today :)

**Comment by cstigler** [comment]
@karamcnair Glad you got it working. And that writeup is awesome!! Great job with it :smiley: 

Would love a PR with updates to those build instructions - they haven't been updated for a while, and it sounds like you found a number of things to change. Plus your version was more clear and had screencaps...
