### ISSUE TITLE
"You must wait for the timer to run out" - well, not actually. 

### ISSUE THREAD

**Issue by aaronantony3** [SelfControlApp/selfcontrol#335]
I want to add few features to the code. However, if I start exploring the code, I will be able to easily unblock my own access to distracting websites even when the app is running (as I will know the app internals and how it works). Any suggestions?

**Comment by cstigler** [comment]
unfortunately i don't believe there's a way around that! as long as you're an admin on your computer, nothing can keep a determined tech-savvy user from restoring their own network access. (and that's probably a good thing.)
