### ISSUE TITLE
SelfControl's helper tool must be run as root.

### ISSUE THREAD

**Issue by nikhilpande-tudip** [SelfControlApp/selfcontrol#337]
I have added selfControl's code in new demo project. I have added everything in project it still gives error that "SelfControl's helper tool must be run as root". What am I missing? Please help on how to get root access.

**Comment by cstigler** [comment]
Hi @nikhilpande-tudip are you building from the actual SelfControl repo, or copying the code into a new project? This repo itself should be working but I can't help you if you're making a new project - outside of our scope, I'm afraid!
