### ISSUE TITLE
file

### ISSUE THREAD

**Issue by kimteeheehe** [SelfControlApp/selfcontrol#339]
i download this program.so i enter file room,click downloaded file
but it doesn't start ,it just download file.

**Comment by cstigler** [comment]
@kimteeheehe sorry, unfortunately I can't understand your question.

To run SelfControl, download the ZIP file from [our website](http://selfcontrolapp.com/), unzip it, drag it into your Applications folder, and then double click it to open it.

Unfortunately we can't provide much more support than that! Hope you can get it working.
