### ISSUE TITLE
Self Control doesn't work with Browsec!

### ISSUE THREAD

**Issue by moniquemus** [SelfControlApp/selfcontrol#342]
I have Browsec to unblock websites at school. It pretty much changes the proxy and accesses the internet through a different country (same with Ultra Surf, Hula, Gom VPN, etc.) CAN YOU PLEASE MAKE IT SO THIS DOESNT WORK COZ I STILL GET DISTRACTED

**Comment by cstigler** [comment]
That would be great, unfortunately there's no feasible way to let SelfControl work with VPNs.
