### ISSUE TITLE
no longer blocking my blacklist

### ISSUE THREAD

**Issue by bcoco** [SelfControlApp/selfcontrol#346]
So, I followed the "Tweaking Max Length" article: https://github.com/SelfControlApp/selfcontrol/wiki/Tweaking-Max-Block-Length-and-Block-Length-Interval and now my sites are no longer being blocked. (And they're not going to be for two more months, because I increased the max length that longc!)

Is there any way to cancel the block that's running, restart the interval, anything?

**Comment by cstigler** [comment]
@bcoco would recommend trying the "Add to Blacklist" feature - add something to the blacklist and it'll refresh the block, that might fix your issues.

**Comment by bcoco** [comment]
Wow, who knew? That seems to have done the trick. Thanks!

**Comment by bcoco** [comment]
It worked once, but is no longer working. If I add a site to the blacklist, my previous blacklisted sites still load.
