### ISSUE TITLE
Trojan in etc/private/hosts - is this normal?

### ISSUE THREAD

**Issue by almeco** [SelfControlApp/selfcontrol#351]
Hi,
Is this normal (fake positive) that kaspersky recognize etc/private/hosts file as infected by a trojan while running self control app? I am confused

Best Regards,
Michal

**Comment by cstigler** [comment]
@almeco if it's just us that modified your /etc/hosts (it only flags it when SelfControl is running), then yes it's just a false positive. I don't know Kaspersky or whether this is normal for them, but it sounds plausible.

If it's flagged even when SC is not running, I'd open up the /etc/hosts file and make sure there's nothing else in there that's actually malicious.
