### ISSUE TITLE
I'm just not sure where to say THANK YOU!

### ISSUE THREAD

**Issue by hannahhoward** [SelfControlApp/selfcontrol#353]
Hello,

  I just want to say thank you to the developers of this application. I have big problems with social media distraction -- sometimes it feels totally out of my control. When things get bad it's nice to have this app to force myself off for a few hours -- it makes a big difference in my work ethic and my happiness levels. So, just to say, thank you -- it really helps people.

Sincerely,
Hannah Howard

**Comment by cstigler** [comment]
You're great - thank you so much @hannahhoward! We usually only get the complaints so this was a really welcome notification in my inbox. Hope it continues to help!
