### ISSUE TITLE
Self Control doesn't block pages using Tor browser

### ISSUE THREAD

**Issue by jkamcc** [SelfControlApp/selfcontrol#355]
The blocking of the pages doesn't work if Tor browser or related browsers are used. 

https://www.torproject.org/projects/torbrowser.html

**Comment by cstigler** [comment]
Hi @jkamcc, this is expected behavior since the Tor browser is an encrypted web browser designed for privacy - we can't look into its web traffic to see what to block. Tor and SelfControl won't be compatible.
