### ISSUE TITLE
Automate SelfControl ?

### ISSUE THREAD

**Issue by catsnotdrugs** [SelfControlApp/selfcontrol#357]
Is there a way to automate SelfControl coming on ?  For instance if I wanted it to be on at all times M-F except for 10am-11am and 10pm-11pm, how would I do so?  I'm pretty noobish with scripts and automating so if possible please ELI5.  Thanks in advance.

**Comment by slambert** [comment]
Yes: https://github.com/andreasgrill/auto-selfcontrol
