### ISSUE TITLE
Help, will SelfControl not let you uninstall it completely?

### ISSUE THREAD

**Issue by Lulululululululululu** [SelfControlApp/selfcontrol#358]
The first few times I used the SelfControl app, it worked like a charm. But seeing as I have to use certain sites on internet to get my job done...I end up not getting my job done after all, seeing as the app will start blocking all of internet from me, leaving me right where I started. After searching the internet, I come to the conclusion that once this app is installed, I am stuck with it on my mac? There is no info to be found as to how to uninstall it, only info on how to fix but keep it.
Please, how to uninstall it completely from my mac?

**Comment by cstigler** [comment]
@Lulululululululululu you can just delete the application from your Applications folder, **after your block is finished**. Just make sure there's no block running when you delete SelfControl, and you're good to go.

(As with every Mac app, this will technically leave a settings file or two floating around, but they're tiny and don't do anything so there's really no harm in leaving them there.)

**Comment by Lulululululululululu** [comment]
Hi Charlie,

Thank you so much for getting back to me so quickly!

I found this on the big internet:

 "If the app you want to remove is downloaded from the App Store, yes, you
can just delete it from the Applications folder. If not, you will need to
use another method.

If the software required an installer, you can be sure that it has
scattered anywhere between a few and a large number of other files in a
variety of different places on the hard drive. Such software should only be
removed using an uninstaller provided by the developer who created that
software. Such installers may be installed in the Applications folder along
with the app being installed, or they may be on the downloaded disk image
containing the installer, or they may even be a part of the installer
itself. (Some installers will ask if you want to uninstall if you run them
and the software is already detected as being installed.)"

Also, how come I have to just leave settings file on my computer, when I
don´t want them there? Excuse if this is an odd question; I am a novice.



2016-04-29 8:56 GMT+02:00 Charlie Stigler <notifications@github.com>:

**Comment by Lulululululululululu** [comment]
"One thing that people commonly do is simply drag an application to the
trash. Fortunately, that actually works in a lot of cases. However, in
other cases, this is an abysmal failure, leaving sometimes dozens of other
components of the software actively running. Worse, in some cases, the
removal of the application can confuse all those other processes, causing
instability and performance problems."

2016-04-29 10:12 GMT+02:00 Luz Yolanda <lz.villaverde@gmail.com>:

**Comment by slambert** [comment]
You got an answer and the issues you're bringing up are not problems in this case. However, if you'd prefer to keep searching on the internet for contrary information, feel free.

**Comment by cstigler** [comment]
The settings files don't do anything and take up just about no space. As the explanation you found says, dragging the app to the trash "actually works in a lot of cases" - this is one of those cases (as long as there is no block running).

If you want to go find and delete those settings files for fun, you can do so, but I don't have a list on-hand of where they end up, so you'd have to go figure that out yourself. Personally I would not bother.
