### ISSUE TITLE
Opening SOCKS Proxy disables blacklist

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [SelfControlApp/selfcontrol#359]
When I open a SOCKS proxy on the machine and tell the network to use it via System Preferences, I wholly bypass Self Control. Even after I turn off the proxy from System Preferences (the ssh connection is still active), it stays bypassed. 

Tested on OS X El Capitan, Safari 9.1

**Comment by cstigler** [comment]
@VTCAKAVSMoACE we don't try to filter through proxies; it doesn't really work if they're encrypted. For now you'll have to avoid using your proxy to use SelfControl.
