### ISSUE TITLE
How do I block the entire tumblr.com domain? 

### ISSUE THREAD

**Issue by feezzo** [SelfControlApp/selfcontrol#375]
I have tried to block tumblr simply by inputting tumblr.com into the blacklist, however this has not worked, I have tried *.tumblr.com and this has not worked either. In the meantime, I have blocked some of the 'example.tumblr.com' blogs that I want to avoid, but I want to block the entire site and every 'example.tumblr.com' sub-blogs that exists. Does anyone know how I can do this?

Any help is greatly appreciated, if this is a previously solved problem then I do apologise and would appreciate being pointed in the right direction.

**Comment by istinson** [comment]
I typed *.tumblr.com and it blocks all of tumblr's subdomains. This issue is closed, right?

**Comment by slambert** [comment]
Thanks @istinson
