### ISSUE TITLE
SelfControl 00:00 bug on OS X 10.6.8

### ISSUE THREAD

**Issue by billi-b** [SelfControlApp/selfcontrol#376]
hi
I can't find the SelfControlKiller app AND can't update for SelfControl 2.0 because of my old 2008 macbook OSX 10.6.8 can not be updated to an 10.7 version. 
please help

**Comment by cstigler** [comment]
Hi @billi-b if you're still experiencing issues, please send me an email at charlie+scgh@charliestigler.com and I can help out.
