### ISSUE TITLE
Killer app for old version (1.5.1)?

### ISSUE THREAD

**Issue by moosenose** [SelfControlApp/selfcontrol#380]
Hi -
I'm running Self Control version 1.5.1 under Snow Leopard, block now stuck on 00:00:00. The FAQ leads me to a link for downloading the Killer app, but this points to a nonexistent page. Is there anywhere else I can get it?
Thanks.

**Comment by cstigler** [comment]
Hi @moosenose please use this link: http://downloads.selfcontrolapp.com/SelfControl-Killer-Old.app.zip
