### ISSUE TITLE
Can't block Google on Chrome?

### ISSUE THREAD

**Issue by cartesy** [SelfControlApp/selfcontrol#381]
On Chrome you can do Google searches from the browser bar. Despite the fact that I've blocked all Google domains, I can do searches on Google and browse.

It's a big issue since from Google, I can easily get myself out of the block whenever I want.

**Comment by cartesy** [comment]
Well, nevermind... As soon as I complained about it, it started to work

**Comment by haffmaestro** [comment]
@cartesy you should close this, glad it started working!
