### ISSUE TITLE
block vpn?

### ISSUE THREAD

**Issue by saltnpixels** [SelfControlApp/selfcontrol#391]
So I am testing this app out to see what it can do.
I see that i can easily bypass with a vpn installed in my browser like hotspotshield which is free on the chrome web store…

Can I block this somehow?

**Comment by saltnpixels** [comment]
ok so reading other issues it sounds like vpn is a weak link for slefcontrol.

what steps can you recommend?

**Comment by cstigler** [comment]
Hi @saltnpixels due to the fact that VPN is (by design) encrypted and not easy to intercept, we don't work with VPN. You can block VPN entirely by blocking whatever port they're using (`*:1723` for example), but you can't block on a site-by-site basis with VPN enabled.

**Comment by saltnpixels** [comment]
Wait. So I can block all vpn's with *:1273 ?
That would be cool.

**Comment by cstigler** [comment]
I'm not an expert on how VPNs work, but yeah assuming it just runs over a port like any other network service, you can block them with SelfControl. The internet says that 1723, 1701, 500, 4500 are all potential ports, so I'd just block all of them and see whether it works. If you know what port your specific VPN runs over, just block that

**Comment by cstigler** [comment]
Unfortunately, I don't know so you'll have to do your own research on that. My previous Googling suggested that ports 1723, 1701, 500, and 4500 were all possibilities.

**Comment by saltnpixels** [comment]
hmmm... looks like the sites use port 443 and blocking that would mean blocking all https.... bleh....
