### ISSUE TITLE
Websites won't unblock after timer.

### ISSUE THREAD

**Issue by tirri1** [SelfControlApp/selfcontrol#401]
Hello, I'm using macOS Sierra with Self Control. When the timer ran down, none of the websites I had on my blacklist unblocked. I have restarted, tried to do another timer and deleted the app and nothing has happened. What should I do?
Thanks.

**Comment by cstigler** [comment]
@tirri1 does the timer show 00:00 when it's done, or does it go back to the Start screen but sites are still blocked?

**Comment by tirri1** [comment]
@cstigler It goes back to the start screen. They're still blocked.

**Comment by cstigler** [comment]
@tirri1 Got it. I'll try to help you figure that out. Can you please send an email to me (charlie+sc@charliestigler.com) with your exact OS version, SelfControl version, a screenshot of your blocklist, and whether you were using a blacklist or whitelist block?
