### ISSUE TITLE
Tried SelfControl Killer app, did not work

### ISSUE THREAD

**Issue by skyshade13** [SelfControlApp/selfcontrol#405]
Hi,

So I woke up today and found the bug where self control gets stuck on 00:00. As per the instructions, here is the order in which I tried things:
-I download the self control killer app, but it did nothing. 
-I downloaded the new self control app 2.0 and hit the 'stuck' button, it did nothing. 
-I tried using an app cleaner, it did nothing. 
-I tried clearing the cache, it did nothing. 
-Then I tried restarting my computer and it did nothing. 

Is there anything else I can do here? I'm not a computer expert so I'm hesitant to start throwing code around. 

I use Chrome and my Mac is currently running El Capitan.

**Comment by skyshade13** [comment]
Ok, so I at least managed to bail all the websites out of the block, but the app (2.1.1 version now) is still stuck. Anything I need to do to try and get it running again?

**Comment by cstigler** [comment]
@skyshade13 there are ways to get the app to fix itself, but the moment you use something like an app cleaner it messes with the internal systems and the self-fixing options probably won't work. Send me an email at charlie+sc405@charliestigler.com with a screenshot of your app and a link to this thread, and I can try to help.
