### ISSUE TITLE
blocking all websites?

### ISSUE THREAD

**Issue by ctf9** [SelfControlApp/selfcontrol#415]
freedom used to just block every website, essentially shutting off my internet for the selected period of time. 

but i got a new laptop and it seems like freedom now works according to a blacklist. is there a way to use it in the old fashion, just blocking all internet access? or do i need to use the blacklist feature instead?

**Comment by cstigler** [comment]
Hi - this project isn't Freedom. This is SelfControl, a different (though similar) app. You can find Freedom at: https://freedom.to/

(SelfControl can also block all websites if you'd like it to - you can set it to a whitelist block and add nothing to the whitelist)

**Comment by ctf9** [comment]
thanks -- i meant to say selfcontrol. that's the one i had. was just looking at other options since i couldn't figure out how to block everything. i'll use the whitelist block method you suggest. thanks!
