### ISSUE TITLE
cmd+shift+T overrides the blacklist

### ISSUE THREAD

**Issue by hovzik** [SelfControlApp/selfcontrol#430]
i have youtube added to my blacklist and, as expected, i get *this site can't be reached* error.
but if i close the tab and then press `cmd+shift+T` to *reopen closed tab* youtube works just fine.
facebook and other sites on the blacklist -- not so much.

p.s. on both safari and chrome, latest version of browsers and selfcontrol.

my mind has finally found a way to cheat the system and it may end up badly.)

**Comment by HisBoilingPoint** [comment]
Smart Idea, also if you simply change your date/time on your computer that works (for facebook or what ever)

**Comment by slambert** [comment]
This is due to caching. 

https://github.com/SelfControlApp/selfcontrol/wiki/FAQ#q-i-blocked-a-website-with-selfcontrol-but-i-can-still-access-the-site-what-do-i-do
