### ISSUE TITLE
Using Endnote and SelfControl at the same time?

### ISSUE THREAD

**Issue by sigros** [SelfControlApp/selfcontrol#431]
Hi. 

Is it possible to add a program like Endnote on the whitelist so it will be able to sync while SelfControl is running? I use a whitelist while working so that everything besides the few websites I need is blocked.

Kind regards

**Comment by cstigler** [comment]
Hi @sigros, to block or whitelist an app you'll need to figure out which servers it connects to, then add those to the list.

Some users have had success doing so with [Private Eye](https://radiosilenceapp.com/private-eye/) and similar tools, but I've never tried it and this is beyond the scope of what I can help you with. You could also try getting in touch with the authors of your app to see if they can just tell you which servers they use. Hope you figure it out.

**Comment by sigros** [comment]
@cstigler - thank you very much.
