### ISSUE TITLE
Feature Request: 11 days?

### ISSUE THREAD

**Issue by ghostis** [SelfControlApp/selfcontrol#439]
Can the time slider go to 11 (days)? One day is really helping, but I would really love to zap an entire week during crunch time. Thanks so much for the app!

**Comment by cstigler** [comment]
Hi @ghostis, yes you can set the slider to go to any number you want, although it's bit of an advanced setting (you're losing the warranty when you start messing with this stuff!). Take a look at this article in our FAQ: https://github.com/SelfControlApp/selfcontrol/wiki/Tweaking-Max-Block-Length-and-Block-Length-Interval
