### ISSUE TITLE
Porting to Swift ?

### ISSUE THREAD

**Issue by divyenduz** [SelfControlApp/selfcontrol#440]
How about the idea? If someone starts to come up with one PR at a time following the [right way](https://martinfowler.com/books/refactoring.html). 

Just want to know your opinion on this. 

Thanks!

**Comment by cstigler** [comment]
Hi @divyenduz! Thank you for the offer to help =)

I personally prefer Objective-C over Swift at the moment for a variety of reasons (not least that the Swift lang and tooling are still unstable). More importantly, I don't think the current language is causing any issues for maintenance, and I'm a big believer in "if it ain't broke, don't fix it".

That said - there are definitely a variety of refactors, code improvements, feature additions, and bug/project process improvements that this project does need. If you're open to contributing in Obj-C, your work would be very much appreciated!

**Comment by divyenduz** [comment]
Thanks for the prompt response. I am open to contributing in objective-c as well, need to brush up my skills though been a while since I wrote objective-c. 

I am looking at a specific feature, multiple lists to be blocked with variable time. Let me see if I can get around with SelfControl CLI to get this, will create a separate issue otherwise. 

Thanks for building this. 

Regards,
