### ISSUE TITLE
Stuck repeatedly after sleep, killer app didn't work

### ISSUE THREAD

**Issue by inchensity** [SelfControlApp/selfcontrol#441]
I have version 2.1.1 

My websites repeatedly get blocked after I wake up my computer from sleep. Using the killer apps didn't work. Clicking the stuck button temporarily fixes the issue as the websites become blocked again when my computer goes to sleep. Even after clearing my blacklist, the app still blocks past websites. 
<img width="403" alt="screen shot 2017-06-24 at 4 26 06 pm" src="https://user-images.githubusercontent.com/29682377/27512586-4c1f03d2-58fa-11e7-9cb5-138245361f45.png">

**Comment by cstigler** [comment]
Hi @inchensity is the timer at 00:00 when you open it? Can you try restarting your computer to see if it's still an issue after restart?

Please note that the old Killer app is not intended for use with versions 2+ and may cause issues if used with them.

If you're still having issues, please send me an email at charlie+sc441@charliestigler.com and I'll try to help you troubleshoot.

**Comment by cstigler** [comment]
For anybody who has similar issues: the problem ended up being a VPN connection through Junos Pulse Secure. If you run Pulse or a similar VPN tool like Cisco AnyConnect to connect to corporate/university servers, **it must be disconnected for the entirety of the time that SelfControl is running.**

These applications have a tendency to save your networking state when they connect and restore to that state when they disconnect - so if you turn them on while SelfControl's running, and turn them off after it finishes, your block will "mysteriously" come back.

If you missed that and are having issues with your block continuously returning, the solution is to disconnect from the VPN, ensure you're disconnected, and then manually unblock your timer one more time. The fix should stick at that point.
