### ISSUE TITLE
Block is too greedy

### ISSUE THREAD

**Issue by moltar** [SelfControlApp/selfcontrol#445]
I blocked `subA.example.com` yet cannot access `subB.example.com`. I am assuming the app is being greedy and blocking the entire top level domain. This is undesirable.

Use case: I participate in multiple Slack groups. Sometimes I want to block all except the work one. Each Slack group has it's own sub domain.

Thanks.

**Comment by cstigler** [comment]
@moltar since it's all hosted on Slack, it's probably all pointing to the same IP address. SelfControl blocks the entire server by IP, so with our current blocking approach there's no way that would be possible unfortunately.
