### ISSUE TITLE
Minor Issue: Typo in the ReadMe.md file

### ISSUE THREAD

**Issue by jamoore5** [SelfControlApp/selfcontrol#446]
There is a typo in the ReadMe.md file

> It can not be undone by the app or by a restart-

The line is missing the word deleting. 

Minor issue but thought I should log it.

**Comment by cstigler** [comment]
Much appreciated, thanks for the report! The README needs a bunch of cleanup, actually - the version history is way out of date (see the [release notes](https://github.com/SelfControlApp/selfcontrolapp.github.io/blob/master/releasenotes.html) on our website for more up-to-date info).

It could be an easy PR if you want to to try your first open-source contribution? :)

Or if not I'll definitely get to this at some point!
