### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by mycroft89** [SelfControlApp/selfcontrol#449]
Not really an issue but more a suggestion. Wouldn't it be great to add an option to set defined schedules? Like activate SelfControl automatically every day from 10:00 to 23:59.

**Comment by cstigler** [comment]
Hi @mycroft89 , thanks for the suggestion. We won't be adding that in the near future to SelfControl core, but if you're technically inclined you can take a look at the third-party auto-selfcontrol project: https://github.com/andreasgrill/auto-selfcontrol
