### ISSUE TITLE
Block youtube website but not youtube embed

### ISSUE THREAD

**Issue by stevebasford** [SelfControlApp/selfcontrol#462]
I'm trying to block the youtube website but still allow youtube embed videos on another website to play. As an example:

https://www.examsolutions.net/tutorials/exam-questions-finding-roots/?level=A-Level&board=Edexcel&module=FP1&topic=1745 => view solution

**Comment by cstigler** [comment]
Hi @stevebasford, unfortunately I don't think this is possible with the SelfControl app as written today. They share a lot of resources.
