### ISSUE TITLE
Timer too long 

### ISSUE THREAD

**Issue by amansheoran24** [SelfControlApp/selfcontrol#464]
I added a modification to the timer, and its set to 34 yrs, mis pressed it for the end of the range years so the highest amount possible. 

My laptop clock only goes till year 2037, need to get it to year 2051 but thats not possible. 

Please suggest solution as I need the websites that are on the block list. 

It reads 299090:40 as the timer, so around 34.1 years.

**Comment by cstigler** [comment]
Hi @amansheoran24 (and anyone else reading), the real solution to this is not to modify the timer to go that long! That's a dangerous modification to make.

If you email me at charlie+gh464@charliestigler.com, I'll help you get the block removed.
