### ISSUE TITLE
[enhancement] Option to use Touch ID instead of administrator password to start block

### ISSUE THREAD

**Issue by pcrutchl** [SelfControlApp/selfcontrol#476]

**Comment by mbrinton01** [comment]
+1

**Comment by slambert** [comment]
I'm all for the idea, but does anyone know if it's possible? Touch ID seems limited to very few things at this point.

**Comment by fredleefarr** [comment]
+1

**Comment by jirikrepl** [comment]
I took a brief look at https://developer.apple.com/documentation/localauthentication

I am wondering if it allows confirming actions with the macOS admin password.
Do you know an app where this is possible?

I know that in Chrome, you still need to type manually the admin password if you want to view your saved passwords.

**Comment by sandykoe** [comment]
Curious if I can be helpful, what functionality does SelfControl use that isn't in the LocalAuthentication framework? What APIs are being used instead?

**Comment by cstigler** [comment]
@sandykoe we currently use the (long-deprecated) `AuthorizationExecuteWithPrivileges` API to run a privileged helper tool. We'll soon be moving to using `SMJobBless` to install a privileged daemon. Off the top of my head not sure if that'll help with the Touch ID dream or not, but research and development welcome!

**Comment by cstigler** [comment]
Confirmed based on [this post on the Apple Developer Forums](https://developer.apple.com/forums/thread/106386): this is not currently possible. Closing but feel free to open if/when Apple ever adds APIs for this!
