### ISSUE TITLE
Edit /etc/hosts file?

### ISSUE THREAD

**Issue by dantuluri** [SelfControlApp/selfcontrol#478]
While doing a project that had to do with editing the host's file, I came across some comments from the Self Control app and realized deleting these redirects would let me bypass the purpose of Self Control. Of course, I wasn't trying to remove the block but was just curious to see what would happen. Is there any way to fix this issue?

How to do it on MacOS High Sierra:
Open up terminal
sudo open /etc/hosts

You'll see what I'm talking about there. You can't edit that file, but there are other ways you can.

**Comment by cstigler** [comment]
Hi @dantuluri, that won't let you bypass the block for long if at all. That's only one of the two ways that SelfControl blocks are applied, so most websites will still be inaccessible even if the hosts file is modified.

In addition, SelfControl checks once per minute to see if the host file has been tampered with, and attempts to restore the block if so.

Anyway, not something we'll be changing in the near future!

**Comment by dantuluri** [comment]
Thanks for the detailed response and answer. I appreciate your explanation.
Would you know what would happen if I tampered with the contents of the **START BLOCK** and **END BLOCK** (there were similar comments) instead of deleting the entire section?

**Comment by cstigler** [comment]
@dantuluri I'm not sure, but I wouldn't suggest it!

**Comment by anmolnehru** [comment]
Hi after tampering with individual entries in /etc/hosts, SelfControl doesn't seem to be able to block the websites (even after a minute). Is this a known issue? SC is able to overcome Editing out all the entries, but not when individual entries are removed. And your previous comment of 

> That's only one of the two ways that SelfControl blocks are applied, so most websites will still be inaccessible even if the hosts file is modified.

Is that true? Because by editing hosts file I'm able to access the websites I've blacklisted.

**Comment by slambert** [comment]
Hm... when you're getting to the point where you're asking this kind of question, it's time to consider writing some code and submitting pull requests. 🙂

**Comment by jeffhu1** [comment]
> Hi after tampering with individual entries in /etc/hosts, SelfControl doesn't seem to be able to block the websites (even after a minute). Is this a known issue? SC is able to overcome Editing out all the entries, but not when individual entries are removed. And your previous comment of
> 
> > That's only one of the two ways that SelfControl blocks are applied, so most websites will still be inaccessible even if the hosts file is modified.
> 
> Is that true? Because by editing hosts file I'm able to access the websites I've blacklisted.

I've also noticed this effect
