### ISSUE TITLE
SelfControl stuck on 00:00:00 but can access websites on blacklist and logs are created as normal

### ISSUE THREAD

**Issue by johncoxon** [SelfControlApp/selfcontrol#486]
I am running SelfControl 2.2.2 on macOS 10.13.2.

My SelfControl timer has reached 00:00:00, and not cleared, but clicking 'Stuck? Stop block manually' doesn't clear the block. I think I started this block yesterday or the day before, and it should have cleared at 5pm on that day. When I click 'Stuck? Stop block manually' a log is successfully created, and my host file is normal, so I can access all the sites on my blacklist, but I can't block them again. I've tried restarting the computer, deleting the cache, deleting the preferences file and reinstalling the app; the behaviour persists.

This isn't a dupe of 457 or 463 because in those cases, the block remained in place and the log file wasn't created upon hitting the 'Stop block manually' button. [I've attached my log to this bug report.](https://github.com/SelfControlApp/selfcontrol/files/1664511/SelfControl-Killer.log)

**Comment by cstigler** [comment]
Hi @johncoxon, sorry you're having issues.

This is a weird one, and I haven't seen exactly this case before. Generally, to figure out whether it should display the timer or the editing window, the app looks at: 1) is there a block in the hosts file, 2) do we have info indicating a block in the "user defaults" (preferences) system, and 3) does a "lock file" exist at `/etc/SelfControl.lock`. In this case, your logs indicate that all of those statements are false, so I'm not sure why your app would still be showing the timer.

My first attempt at understanding this is to *ask you to manually verify the above statements*, just to make sure that the unblocking script isn't checking them incorrectly for any reason. To do that, you can use the following Terminal commands and copy/paste the output back in this thread:
```
cat /etc/hosts
defaults read org.eyebeam.SelfControl
ls -la /etc/SelfControl.lock
```

Also: is there anything unconventional about your computer setup that might be worth investigating? For example: VPN usage, unusual user account setup, clock set to a weird time, or something like that.

**Comment by johncoxon** [comment]
Thank you, the output from Terminal is below. I do have a VPN configured on the machine but it's not currently turned on, and turning it on and trying to clear the block also does nothing.

```
$ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 

$ defaults read org.eyebeam.SelfControl
{
    BadgeApplicationIcon = 0;
    BlockDuration = 135;
    BlockStartedDate = "2018-01-22 14:46:48 +0000";
    GetStartedShown = 1;
    HostBlacklist =     (
        "facebook.com",
        "reddit.com",
        "messenger.com",
        "chaoscards.co.uk",
        "playstation.com",
        "swdestinydb.com"
    );
    "MASPreferences Selected Identifier View" = GeneralPreferences;
    "NSWindow Frame SUUpdateAlert" = "330 300 620 392 0 0 1280 777 ";
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2018-01-30 17:16:04 +0000";
}

$ ls -la /etc/SelfControl.lock
ls: /etc/SelfControl.lock: No such file or directory
```

**Comment by cstigler** [comment]
Hi @johncoxon, looks like there might be something still in `defaults` after all, not sure why it didn't show in your log.

Try quitting SelfControl, then entering in Terminal `defaults delete org.eyebeam.SelfControl` to clear it, then restarting SelfControl.

**Comment by johncoxon** [comment]
That did the trick, thank you! Might it be worth adding to the FAQ for anyone who sees similar behaviour in the future?

**Comment by cstigler** [comment]
Great! Good question on the FAQ - I'm inclined to leave it off right now since this is the first case of this type I've seen (missing the "F" 😉), but it's a handy thing to know for the future.

**Comment by kmh1000** [comment]
I had the exact same problem and the terminal command fixed it. Thanks! I'm not sure 2 people having an issue is worth adding to the FAQ yet, but it might not be so isolated.
