### ISSUE TITLE
[Enhancement] Localized label may cut off in longer languages

### ISSUE THREAD

**Issue by redmer** [SelfControlApp/selfcontrol#490]
Some languages require longer labels to get across the same meaning. The button "Add to Blacklist" in the counting-down window translates in Dutch to "Voeg toe aan zwarte lijst" and requires a wider label. See image below.

Suggestion: widen the button (or its window) to fit its text. I would take a look and do a pull request, but my Cocoa experience is too long ago. Thanks for this app!

![image](https://user-images.githubusercontent.com/12477216/35728963-89e01b94-080d-11e8-8c8d-90e393e4c16a.png)

**Comment by cstigler** [comment]
Fixed this and a number of similar bugs by converting the app to auto-layout! See commit e96beddffe8f6480e6b62c76c63b12701f61ffdc

You should see the update next time I make a release...
