### ISSUE TITLE
blacklist blocked since a month!!

### ISSUE THREAD

**Issue by garneele** [SelfControlApp/selfcontrol#502]
I deinstalled the self control app and also ran the self control killer code but nothing worked. :( who can help me??

**Comment by cstigler** [comment]
@garneele uninstalling the app while the block is running is bound to cause issues. Please check out our FAQ which has relevant info.

In particular: "First, download the latest version of SelfControl from selfcontrolapp.com (replacing your older version). Then open it, and the timer should read 00:00 (assuming the block should be over). Leave that timer window open for 10 seconds, and the "Add to Blocklist" button will change to "Stuck? Stop block manually." Use that to remove your block."
