### ISSUE TITLE
Is there a way to allow a subdomain within a blocked domain?

### ISSUE THREAD

**Issue by diegodossantos** [SelfControlApp/selfcontrol#504]
I'd like to block Facebook for a month, but allow Facebook events.

Thanks!

**Comment by cstigler** [comment]
Unfortunately, I don't think you can do this exactly. But you can just blacklist the subdomains you want to block, if that would help...

**Comment by diegodossantos** [comment]
Thank you! Just saw you work for Workday. I used to live right next to their headquarters (?) in Pleasanton, across the street from the mall.
