### ISSUE TITLE
Random websites being blocked when SelfControl deleted while block was running

### ISSUE THREAD

**Issue by 21michalj** [SelfControlApp/selfcontrol#506]
I trash deleted SelfControl while the block was running, and now random websites (not related to the ones I had only blacklist) say that they can't open and then sometimes they work. Any replies would be useful and I would like to know how I can delete all of the SelfControl resources from my mac. It could also be a virus I have on my computer but I don't know.

**Comment by cstigler** [comment]
Hi @21michalj, that sounds like it may not be related to SelfControl, but deleting it while the block is running is bound to cause problems.

My suggestion is to install the application again and open it. When the timer runs out, the block will be removed. If for any reason it can't be removed, the timer will stay at 00:00, and after 10 seconds you'll see a button "Stuck? Stop block manually" which you can use to clear the block.

**Comment by 21michalj** [comment]
HI @cstigler, I have solved the problem. The block ended even though the application was deleted and now my computer works fine for now. If the problem continues to exist, I will follow your suggestion.
Many thanks
