### ISSUE TITLE
how do I append a url to Blacklist

### ISSUE THREAD

**Issue by Freakwill** [SelfControlApp/selfcontrol#509]
I use `defaults write org.eyebeam.SelfControl HostBlacklist -array facebook.com news.ycombinator.com` to set Blacklist, but how do I append a url to Blacklist?

Can I set BlockDuration more than one day?

It is really an awesome app.

**Comment by cstigler** [comment]
Hi @Freakwill, the `defaults` preferences system and command line tool is built into Mac OS X, not something maintained for SelfControl, so I don't know much about its capabilities. Of course you can always add a URL to the blacklist using our GUI Mac app, which we do maintain (most users do not use the command line).

I read the docs for `defaults` and it says it has an `-array-add` flag that should do what you want. i.e. `defaults write org.eyebeam.SelfControl HostBlacklist -array-add 'news.ycombinator.com'`.

And yes, you can use the command line to increase the maximum block duration. Take a look here for more details: https://github.com/SelfControlApp/selfcontrol/wiki/Tweaking-Max-Block-Length-and-Block-Length-Interval
