### ISSUE TITLE
Multiple blocks with varied block time

### ISSUE THREAD

**Issue by divyenduz** [SelfControlApp/selfcontrol#513]
I was exploring the CLI to have various blocks with varied lengths. But I could only find the `defaults` way of blocking. My `self-control.sh` file looks like this: 

```
defaults write org.eyebeam.SelfControl BlockDuration -int 60
defaults write org.eyebeam.SelfControl HostBlacklist -array twitter.com linkedin.com
defaults read org.eyebeam.SelfControl
sudo /Applications/SelfControl.app/Contents/MacOS/org.eyebeam.SelfControl $(id -u $(whoami)) --install
```

Can I use `defaults write <new identifier>` and host multiple blocks (will try it out, seeking best practices with this issue). 

Can I read the current active blocks/their duration? If no, will this be a feature request you would accept, I can take up the implementation part.

**Comment by cstigler** [comment]
Hi @divyenduz it would be pretty serious work to modify SC to handle multiple blocks - all of the logic is built assuming one block at a time. Everything from the host-file blocking to the firewall blocks to the timer logic would have to be modified.

In terms of would I accept an implementation of this feature - definitely depends on how much it would complicate the code and/or clutter the UI. If you have a proposal there please suggest it!
