### ISSUE TITLE
Setup via cronjob

### ISSUE THREAD

**Issue by divyenduz** [SelfControlApp/selfcontrol#514]
I am using the script defined [here](https://github.com/SelfControlApp/selfcontrol/issues/513) but it asks for a password when I run it from CLI. Can I configure it to run as `root`, so, it does not ask for password anymore. 

I understand that supplying password to cron via a hacky way is another option. Again, just seeking opinion on this usage approach.

This is for my local machine, hence, I can actually type out the password in plain text on the file system.

**Comment by cstigler** [comment]
@divyenduz Hmm, not sure on this one. You could try just setting the SUID bit and seeing what happens, but I'm not really sure - haven't tried to run it that way before.

**Comment by majjoha** [comment]
I've SelfControl scheduled to run daily as well. I use `launchd` rather than `cron`, though.

In `/Library/LaunchDaemons`, I have a file called `io.mjj.antiprocrastinate.plist` with the following contents:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>io.mjj.antiprocrastinate</string>
    <key>ProgramArguments</key>
    <array>
      <string>/bin/bash</string>
      <string>/Users/mathias/.local/bin/antiprocrastinate</string>
    </array>
    <key>StartCalendarInterval</key>
    <array>
      <dict>
        <key>Hour</key>
        <integer>09</integer>
        <key>Minute</key>
        <integer>30</integer>
      </dict>
    </array>
  </dict>
</plist>
```

Daemons in `/Library/LauncDaemons` run with root permissions, so you do not need to pass a password once it is properly loaded. In `/Users/mathias/.local/bin/antiprocrastinate`, I then have the following file as an executable:

```bash
#!/bin/bash

defaults write org.eyebeam.SelfControl BlockDuration -int 360
/Applications/SelfControl.app/Contents/MacOS/org.eyebeam.SelfControl 501 --install
```

**Comment by jlaw9** [comment]
@majjoha the launchd setup isn't working for me. If I run the `org.eyebeam.SelfControl` / `selfcontrol-cli` with sudo, a gui prompt for the admin username and password pops up, and I can't figure out how to have the `launchd` script automatically fillout those fields.

Right now, `selfcontrol-cli` is giving me this error, even though it's being run as root: 
```
ERROR: Failed to authorize installing selfcontrold with status -60007
```

Anyone figured out a workaround??

**Comment by majjoha** [comment]
I have not used SelfControl in a while, so I am not entirely sure why you are running into this issue. I'll let you know if I do at some point and find a solution.
