### ISSUE TITLE
Support macOS Mojave Dark Mode

### ISSUE THREAD

**Issue by DavidMunch** [SelfControlApp/selfcontrol#520]
A minor thing, but it would be appreciated. :)

**Comment by Matthewspear** [comment]
A rebuild with Xcode 10.2 in dark mode produces this:
<img width="732" alt="Screenshot 2019-04-21 at 03 00 34" src="https://user-images.githubusercontent.com/1668863/56464455-d7279e00-63e1-11e9-830f-6875f3e4f7bf.png">
<img width="513" alt="Screenshot 2019-04-21 at 03 00 37" src="https://user-images.githubusercontent.com/1668863/56464456-db53bb80-63e1-11e9-8f28-3e2e428f76ae.png">

Only major change would be the NSTableView in the DomainListWindowController.

**Comment by edjw** [comment]
It's still like this on macOS 10.15.1

<img width="692" alt="CleanShot 2019-11-01 at 09 39 04@2x" src="https://user-images.githubusercontent.com/6547979/68016016-7a0f7d80-fc8b-11e9-8e82-4bf3c3574b8f.png">

**Comment by koenige50** [comment]
> It looks like this on macOS 10.15.1 with Self Control v2.3. The + and - buttons, the Import button and Blacklist / Whitelist radio buttons aren't visible or clickable (!) any more either.
> 
> <img alt="CleanShot 2019-11-01 at 09 39 04@2x" width="692" src="https://user-images.githubusercontent.com/6547979/68016016-7a0f7d80-fc8b-11e9-8e82-4bf3c3574b8f.png">

I second edjw. It looks the same to me on Mojave, making SelfControl 2.3 unusable. Until there's a fix, I am stuck with SelfControl 2.2.

**Comment by cstigler** [comment]
Good news everybody! @jiayi-zhou fixed this and it looks great now in Dark Mode. Check out version 2.3.2.

**Comment by koenige50** [comment]
Upgraded to 2.3.2 and the blocklist itself looks good on Dark Mode now.
But the problem with +/- buttons, Import button and Blacklist / Whitelist radio button continues intermittently.
It's strange. On starting the app, sometimes it displays correctly, sometimes not. I tried doing it a dozen times in sucession and it's 50/50 one way or the other, apparently at random.
