### ISSUE TITLE
Block Facebook, affects WhatsApp

### ISSUE THREAD

**Issue by Novaera** [SelfControlApp/selfcontrol#524]
Hi,

Recently installed in Mojave and work perfectly, but I notice that always enable this for block Facebook, I can't send images or documents via Whatsapp Desktop (Probably because Whatsapp use some services of Facebook for send this) and I used a lot this for work (The customer not use Slack or something similar).

I know how SelfControl Block pages vía hosts file:

```
# BEGIN SELFCONTROL BLOCK
0.0.0.0 facebook.com
::      facebook.com
0.0.0.0 www.facebook.com
::      www.facebook.com
# END SELFCONTROL BLOCK
```

It would be great if the blockade will only cover the main page and not alternative services.

**Comment by Name153** [comment]
Are there any workarounds that would block the main Facebook newsfeed without interfering with WhatsApp messages?

**Comment by cstigler** [comment]
You can play around with finding some random domain that's used only by News Feed and not by WhatsApp and trying to block that, but unfortunately there's no great way to do that with SelfControl right now. They share servers so it's hard for us to block one without the other...

**Comment by yangcht** [comment]
The problem persists. Not sure if SelfControl can be modified to identify clients. So that it can whitelist Whatsapp client but leave Browsers blocked from Facebook.com

**Comment by iqbalmalik89** [comment]
@cstigler  Can you provide the URL which only block newsfeed but not associated apps like whatsapp?

**Comment by synchronizing** [comment]
The domain fb.com seems to do the trick. It will block resources from loading when accessing facebok.com (so it hangs on load), but won't block WhatsApp service.

**Comment by LucianoAngel** [comment]
> The domain fb.com seems to do the trick. It will block resources from loading when accessing facebok.com (so it hangs on load), but won't block WhatsApp service.

Works properly with fb.com
