### ISSUE TITLE
How can I block everything except my app of the Mail? In a MAC

### ISSUE THREAD

**Issue by Felicar** [SelfControlApp/selfcontrol#526]
Please, I need to block everything except my app Mail. I have a MacBook Pro. Thanks

**Comment by cstigler** [comment]
Hi @Felicar, you can import your Mail servers into your blocklist using the Import button at the bottom of the Edit Blocklist window. Then just switch it to a "Whitelist" block and you should get that behavior. Note that whitelist blocks can behave unpredictably, so you should test it with a short block (15 min) before diving into a long one.
