### ISSUE TITLE
Timer stuck at 00:00:00 on v2.2.2

### ISSUE THREAD

**Issue by drawded** [SelfControlApp/selfcontrol#529]
A couple of weeks ago I started a timer but decided to end it prematurely by changing the computer's time forward until after the block end time, then change it back to normal time. I've used this trick a couple of times before and it always worked but it didn't work this time. The sites were unblocked, but the program is stuck on the timer window and I can't start another block or edit the blocklist. When I open the program it's stuck on the timer, and when i click on the manually disable timer button that appears after a few seconds, it asks for my password but when I enter it it doesn't do anything.

Screencapture demonstration: https://streamable.com/jcpc0

**Comment by cstigler** [comment]
Hi @drawded - seems likely the clock changes messed something up in the unblocking process, unfortunately.

After you enter your password to manually disable the block, it should create a SelfControl-Killer.log file in your Documents folder with details about what it's trying to do. Can you look for that?

Please email that log file to me (charlie@charliestigler.com), or let me know if you can't find it, and I'll try to help you debug.
