### ISSUE TITLE
When running, Self Control blocks website not on my Blacklist 

### ISSUE THREAD

**Issue by m00nbunny** [SelfControlApp/selfcontrol#530]
Hello,
I love this application and it has been enormously helpful to me. However, whenever it is running, it blocks Instagram, which I unfortunately need for work. The only sites I typically block are FaceBook, Twitter, and Tumblr. Perhaps there is some connection between those sites that forces Instagram to be blocked? Either way, I can't access it while Self Control is running. I have never tried using a kill program or altering it any way in terminal. Restarting my browser/computer doesn't change anything. Is there a solution to this?

Thanks and Best,

m00nbunny

**Comment by cstigler** [comment]
@m00nbunny unfortunately this usually just indicates that the sites on your blocklist run on some of the same servers. Facebook owns Instagram, so my guess is that they rely on the same servers on the backend... so blocking Facebook blocks Instagram.

**Comment by m00nbunny** [comment]
Thanks!
