### ISSUE TITLE
Any way to use TouchID on MacBook Pro (or new MBA with TouchID) for authentication?

### ISSUE THREAD

**Issue by jalustig** [SelfControlApp/selfcontrol#535]
I use a long password and TouchID on my MacBook Pro for authentication (where it's available). Is there a way to use TouchID to give the app elevated privileges when SelfControl is trying to start a block?

**Comment by cstigler** [comment]
Not currently, but it has been suggested! Follow issue #476 for updates (if it happens). If you're a developer and interested in looking into it, we also take pull requests :)
