### ISSUE TITLE
Allowing iMessage and Facetime

### ISSUE THREAD

**Issue by ilemhadri** [SelfControlApp/selfcontrol#537]
I want to still be able to use iMessage and Facetime while Self Control is active. Is that feasible? Seems that they both use a range of addresses, like 17.173.0.1 to 17.173.255.255, and don't see a way of adding these simply to SelfControl.

Edit:
what I have tried so far:
adding push.apple.com
adding wildcard *.apple.com

**Comment by cstigler** [comment]
@ilemhadri I don't know much about the iMessage/FaceTime services, but a fun secret fact about SelfControl is that we support IP range blocks as CIDR subnet ranges. Ex for the range of addresses you gave as an example, `17.173.0.0/16` should work to block it if you enter that on . Good luck!

**Comment by ilemhadri** [comment]
@cstigler thanks. Isn't there a documentation for this type of things available? That would be helpful.

**Comment by cstigler** [comment]
Unfortunately there is no documentation on this one that I could find. But
if you feel like writing some, it would be much appreciated!
