### ISSUE TITLE
00:00:00 time stuck V2.2.2

### ISSUE THREAD

**Issue by dusk039** [SelfControlApp/selfcontrol#538]
Hi, I'm having an issue where my time ran out and my sites are unblocked but I can't start a new block.
I have self control version 2.2.2 and Mac OS X 10.12.4

I waited 10 seconds and clicked the manually end block. It said it was successful but remained stuck on 00. 
I shut down and restarted my computer after this but upon opening the app it is still at 00.
I deleted the self control app and re-downloaded it and it is still at 00.
I looked at the SelfControl-Killer.log, the bottom reads: 

SUCCESSFULLY CLEARED BLOCK!!! Used [BlockManager forceClearBlock]
Deleting the defaults returned: 1

Failed to remove PF token file.

Removed anchor file successfully.

===SelfControl-Killer complete!===

Any ideas on how to fix this? I would love to keep using this app!

**Comment by cstigler** [comment]
Sorry to hear you're having issues with SelfControl! Here's my suggestion:

1. Open your Terminal (Applications --> Utilities)

2. Type the following two commands *very carefully*, hitting enter after each one:
```
sudo rm /etc/SelfControl.lock
defaults delete org.eyebeam.SelfControl
```

3. Record the output of those commands (copy/paste them into a note or something) in case you need them later

4. Restart your computer and open SelfControl.

Let me know if that doesn't work!
