### ISSUE TITLE
Selfcontrol Support

### ISSUE THREAD

**Issue by zhaw-peterth1** [SelfControlApp/selfcontrol#541]
Is there any risk in using this app in upcoming MacOS releases and then I will never be able to access the blacklists website. In case selfcontrol somehow has an internal error. Or is it pretty safe that it will always end and never block up.. Just scared one day I start it and then it never goes away..

**Comment by cstigler** [comment]
Hi @zhaw-peterth1, most users use SelfControl and never have any problems. Every once in a while, a user does have a problem with a block sticking on, but they've always been resolved with simple troubleshooting steps (they usually end up emailing me 🙃).

That said, this is free software that comes with no warranty or support, so keep that in mind!
