### ISSUE TITLE
Time different than what I requested.

### ISSUE THREAD

**Issue by CarawayCarter** [SelfControlApp/selfcontrol#542]
I had the app running for 15 mins and then took a break and did another 15 min interval. This last time it took a long time to load and its now running for 16 hours. This is the first time this has happened to me.

**Comment by cstigler** [comment]
@CarawayCarter is it possible you changed your time zone during the block? That's about the only way I can imagine this one happening

**Comment by CarawayCarter** [comment]
I guess I'll see in 11 hours when it's finished.

**Comment by CarawayCarter** [comment]
yup, I was a dunderhead, I don't know how it did that. whoa 17 hours.

**Comment by cstigler** [comment]
Sounds like you figured it out!
