### ISSUE TITLE
How to run migration assistant without hiccups

### ISSUE THREAD

**Issue by venkatasg** [SelfControlApp/selfcontrol#551]
I'm going to migrate to a new Mac and I'm looking into what could cause issues. Ideally what I want to do is uninstall SelfControl on my current Mac(including all files that may cause issues), run migration assistant to transfer everything to the new Mac, and then install it anew. Other than deleting SelfControl, and editing /etc/hosts file back to its default, is there anything else I need to do(or should I not worry, since Migration Assistant won't transfer those settings files anyway)?

**Comment by cstigler** [comment]
The only thing you need to do - and this is important - is make sure that the SelfControl block is *not running* whenever you do any sort of system migration.

`/etc/hosts` is left unchanged when a block is not running, so you shouldn't need to do any manual editing there. Just make sure SC isn't running, and transfer things over as normal.

**Comment by venkatasg** [comment]
Thank you!
