### ISSUE TITLE
Blocking Youtube in Safari not working

### ISSUE THREAD

**Issue by cartfjord** [SelfControlApp/selfcontrol#552]
Hi, I cannot get Selfcontrol to block Youtube correctly in Safari.
I've added "youtube.com", "youtu.be", "www.youtube.com" etc. to the blacklist. However, I suspect that the bug is due to some caching in safari. If all cookies, databases and so fourth are cleared, the SelfControl works as intended. It also works in "private tabs" in Safari. In Google Chrome it also works flawlessly. 

I also found this thread mentioning ad blockers:
https://github.com/SelfControlApp/selfcontrol/issues/540

This seems not to be the case for me, as disabling all extensions does not solve or change the behaviour. Any ideas?

Best regards,
Christian A. Cartfjord

**Comment by cstigler** [comment]
Hi Christian! If it works reliably after clearing your cache, then yes, I'd say caching is probably the issue. We try to clear caches automatically when we start a block, but it sounds like that wasn't working perfectly in your case.

If so, then the workaround for now is to manually clear your browser cache after starting a block. A little annoying, but it'll work!

If you're a software developer and have time to investigate, it'd be great to investigate and improve the built-in cache-clearing also. Let me know if so and I can help you find the right parts of the code!

**Comment by cartfjord** [comment]
Yes, that would be great! I will have a go at it 

Best regards,
Christian

**Comment by cstigler** [comment]
Awesome! The function to look at is `clearCachesIfRequested` in HelperCommon.m: https://github.com/SelfControlApp/selfcontrol/blob/854678d77b27ac45cb7a295381838ebc1a94affc/HelperCommon.m#L174

Would love to see a PR if you can figure it out :)
