### ISSUE TITLE
Block timing issues with self control + Erratic Random site blocking even when not on blacklist 

### ISSUE THREAD

**Issue by aaryanb** [SelfControlApp/selfcontrol#553]
Note: I have auto self control installed as well... and i'm on version 2.2.2 self control... Yes, I have posted on the auto self control github too, but not many people check over there... and anyways the issue are probably self control related not auto self control related.

Firstly:
I have back to back blocks where 7pm to 0:30 I've got everything in my blacklist blocked.. then 0:30 to 0:40 only specific sites blocked from a specific blacklist (method here) then 0:40 to for example like 5am i've got everything blocked again, but sometimes it doesn't go from my my specific blacklist back to the block everything immediately and it takes like a random amount of time to 'flip the switch and start blocking'... the same goes with even non back to back blocks for example ok 3pm to 8pm i've got a block and i reach home at 4pm and well its not blocked although it should have started blocking from 3pm.. the computer is off from 2pm to 4pm so does it sometimes not block/start the app or something when the computer is off?

Also:
Sometime sites randomly will just be blocked even if not on blacklist and then suddenly later in the day they are accessible again (since they were never on the blacklist to begin with).. any idea why this happens?

Finally:
so I have this site (NOT blocked) called (i've made up the name but the domain structure is the same)
kais.ac.jp which i can easily access.. however similarily the site learningspaces.kais.ac.jp is blocked and i've checked about 3 times its not on my blocklist.. but still for some reason its blocked even if the site itself (kais.ac.jp) is not blocked. Any idea what to do here?

**Comment by cstigler** [comment]
Hi @aaryanb,

Issue #1 sounds like it needs to be dealt with in auto-selfcontrol. It may involve problems in SC also, but hard to say without investigation.

Issues #2 and #3 are unavoidable with our current blocking system: we block IP addresses as well as domain names. So if two sites share servers - or perhaps rely on the same backend service. That certainly sounds like the case with #3 since it sounds like sites are run by the same place.

**Comment by aaryanb** [comment]
@cstigler That still doesn't make sense especially for #3 since kais.ac.jp and learningspaces.kais.ac.jp are BOTH NOT BLOCKED so even if they share the same server since neither are blocked in the first place then why would one just block? kais.ac.jp is not blocked and learningspaces.kais.ac.jp is not blocked yet erratically learninspaces.kais.ac.jp will become inaccessible and then accessible again.

**Comment by cstigler** [comment]
@aaryanb I'm not familiar with the site so don't know about the specifics, but the most likely reason those sites would be blocked by SelfControl is if they share a server with something on your blocklist. Beyond that you'll need to do your own investigation!
