### ISSUE TITLE
Remove time limit

### ISSUE THREAD

**Issue by janklosowski** [SelfControlApp/selfcontrol#559]
I want to be able to block sites for many days. What's the point of having a 24h limit anyway?

**Comment by cstigler** [comment]
@janklosowski see here: https://github.com/SelfControlApp/selfcontrol/wiki/Tweaking-Max-Block-Length-and-Block-Length-Interval

**Comment by janklosowski** [comment]
@cstigler This solves my problem. Thanks. The dream feature: different schedules for different apps.
