### ISSUE TITLE
How to create my own list file?

### ISSUE THREAD

**Issue by rfschubert** [SelfControlApp/selfcontrol#566]
Create my own domain list is not a easy task...
I want to add to a file hundreds of URL's to block, but add one by one will be eternal...

How can I create my own file to import?

**Comment by cstigler** [comment]
If you have an Excel spreadsheet or other line-by-line file, you can copy/paste them into one entry on the blocklist and it'll automatically split them by lines into separate entries. That's probably easiest.

You could also try to reverse engineer the file format - it's binary but not that complicated. But still sounds like less fun.
