### ISSUE TITLE
doesn't work anymore. home doesn't show start button.

### ISSUE THREAD

**Issue by mind-ashish** [SelfControlApp/selfcontrol#567]

**Comment by EyeRoe** [comment]
Ditto. I only have a timer at 0 and no way to reset. I've tried uninstalling and reinstalling. 
![Screen Shot 2019-08-13 at 5 05 54 AM](https://user-images.githubusercontent.com/29494226/62940293-16f70480-bd88-11e9-8b9c-aeba3c7c3b9c.png)

**Comment by cstigler** [comment]
@EyeRoe try that button labeled "Stuck? Stop block manually"
