### ISSUE TITLE
Weird side effect: The app appears to block Gitlab

### ISSUE THREAD

**Issue by nehbit** [SelfControlApp/selfcontrol#568]
Hey folks,

Love the app! I'm having this problem lately that I can't really make much sense out of. Whenever I have the self control open and active, I cannot seem to access Gitlab. 

It redirects to about.gitlab.com and it fails there. If I go to the sign-in page of Gitlab, the page opens, but it does not load the CSS. https://gitlab.com/users/sign_in

The obvious thing — no, I don't have Gitlab on my self control block list. I also checked my browser, I can't access Gitlab through any browser. I tried Chrome, Safari, Firefox and even Lynx. 

DNS is out, too. changed it, wiped the cache, no dice. 

This has been going on for a few months, so it's not a fluke. It also starts to work the moment self control block. 

Any idea what might be causing this issue?

**Comment by cstigler** [comment]
@nehbit unfortunately it's probably shared servers between GitLab and something in your list. Given that it's CSS only, potentially it's their CDN that's getting caught.

If you want to debug, two ideas are: 1) go to Chrome inspector and see exactly which hostnames have failing requests, and 2) remove sites from your blocklist one by one and see which one is causing it

**Comment by lkaybob** [comment]
![image](https://user-images.githubusercontent.com/5652281/68456166-773efa80-0240-11ea-9655-394288e8b3a2.png)
I've spared some time to dig in this problem, and it seems that getting rid of `forbes.com` from the list works for me :)
