### ISSUE TITLE
Easily removing block using terminal commands

### ISSUE THREAD

**Issue by jaikb** [SelfControlApp/selfcontrol#571]
So I wanted to start writing a script to start a block according to my schedule. So I looked up how to start a block in the terminal and I found that if you run this command in the terminal

`$ sudo /Applications/SelfControl.app/Contents/MacOS/org.eyebeam.SelfControl $(id -u $(whoami)) --install`

it will start a block. But my problem is I mistakenly ran this command twice while the block was active, then suddenly it cleared my current block. You can see this [here](https://imgur.com/a/g8yYBV2)

This is a major problem for me because now my brain knows a way to get out of the block. If I ever "need" to go onto YouTube or something, I find myself just clearing the block. Can this be fixed?

**Comment by cstigler** [comment]
Hey Jai, yep have heard this one before! It sounds like you've got some development experience, would you be up to try to fix it and submit a PR? Otherwise it'll probably be a while before I get to this one, unfortunately.

**Comment by jaikb** [comment]
Okay! I'll try to fix it then. Thank you.

**Comment by hjorne** [comment]
Also ran into this problem, here is a PR with a proposed fix: https://github.com/SelfControlApp/selfcontrol/pull/572

**Comment by zman051** [comment]
I have this issue where it is easy to remove by modifying the htaccess file...
