### ISSUE TITLE
Extend Block Timer allows remaining block time to be longer than 24h

### ISSUE THREAD

**Issue by dtrts** [SelfControlApp/selfcontrol#576]
Not sure if intended.

**Comment by cstigler** [comment]
@dtrts It was intended - are you glad or concerned about said change?

**Comment by dtrts** [comment]
Personally i'm glad as I will use it this way. 

I had assumed the limit was there to stop users from blocking vital websites for an extremely long time and having to come to your team to help remove the block.

**Comment by cstigler** [comment]
👍 you're right, it was there for that reason. I'm hoping that allowing it in this small way will add some flexibility without increasing the support issues too much. We'll see how it goes!
