### ISSUE TITLE
Websites still blocked after time up AND app uninstalled

### ISSUE THREAD

**Issue by drewwils** [SelfControlApp/selfcontrol#579]
Even after the time ran out, websites are intermittently blocked (some but not all - for example BBC and NY Times were on my blacklist, but only NY Times is being blocked) even after I uninstalled SelfControl.  No problem connecting to NY Times using a VPN.

**Comment by cstigler** [comment]
Hi @drewwils, try clearing your browser caches and then restarting your computer.

If you're still having issues after that, please re-download SelfControl, start another block for 15 minutes, and wait for that block to expire.

If you're still having issues after that, let me know...
