### ISSUE TITLE
htaccess easy override

### ISSUE THREAD

**Issue by zman051** [SelfControlApp/selfcontrol#580]
Is there a way to prevent modifying the htaccess file to allow access to the blocked webstie(s)?

**Comment by cstigler** [comment]
Hi zman051, I'm not sure that I know what you mean by this. The `.htaccess` file is generally used on webservers, not to manage your own access to websites. Are you maybe thinking of your `hosts` file?

In either case, unfortunately the answer is probably that we can't prevent you from modifying files on your own computer. But we do make it hard with the hosts file: we use a backup block via firewall, and also attempt to detect tampering and re-add the block.
