### ISSUE TITLE
Feature request: DNS LOCK

### ISSUE THREAD

**Issue by Pookeyblow** [SelfControlApp/selfcontrol#581]
It would be great if there was a way to lock DNS so it's impossible even for an admin to change it. Instead of typing in a website to block, you specify one or more DNS adresses to lock. Or it could just block DNS changes on your system.

Kinda like this: https://www.freelancer.ca/projects/c-programming/modify-selfcontrol-app-lock-dns/

CleanBrowsing.org has some DNS filters for security, adult content and so on. The great thing about these filters is that you don't have to create a list of thousands of websites to block, which is practically impossible to do. The problem is that I as an admin can change the DNS any time I'm tempted to.

This will help a lot of people out there.

**Comment by cstigler** [comment]
Hey Pookeblowy, that would be nice, but there's really no way to block an admin from making changes to their DNS config. We could make it harder but not really impossible. If anybody has ideas on how to implement it feel free, but otherwise closing for now!

**Comment by Pookeyblow** [comment]
I guess MacOS Catalina has something that works with Screen Time Passcode
