### ISSUE TITLE
how i can permanently disable some websites?

### ISSUE THREAD

**Issue by zeroDevOne** [SelfControlApp/selfcontrol#596]
Hi, can you please write how i can permanently disable some websites. i need a webfilter with local account. please, please, please

**Comment by cstigler** [comment]
SelfControl isn't really designed for permanent blocking. That said, some users have used it for that purpose by extending the maximum block length to an extremely long duration (i.e. years) and turning on a very long block. Not recommended and we won't help you if it breaks, but you can do it.

**Comment by zeroDevOne** [comment]
Yeah i know, i found a way to set selfcontrol to block by mount, it will good you can add filtering by regex ? or web filter,  without connection to service somewhere as everybody doing  and tracking everything if think get pay for this app if it will be
