### ISSUE TITLE
"Extend Block Timer" feature has no effect if default 15 minute value is removed

### ISSUE THREAD

**Issue by benmobbs** [SelfControlApp/selfcontrol#600]
Long time user. Say for example you want to extend block by 4 hours, if you 0 the 15 minute value that's the default so "4 hours and 00 minutes" in the pop-up dialogue then no time will be added. You have to leave the 15 minute value in. So "4 hours and 15 minutes" input will work but  "4 hours and 00 minutes" won't. Seems for some reason it's expecting a minimum value of 1 minutes or 15 minutes and won't accept 0 minutes.

This is on OSX 10.11.6.

**Comment by cstigler** [comment]
Hi @benmobbs, thanks for the report. On my system typing a 0 works. Can you try it with one zero instead of two (i.e. `0` instead of `00`) and see if that changes things? What exactly happens when you click enter if you've entered a zero?

**Comment by benmobbs** [comment]
> Hi @benmobbs, thanks for the report. On my system typing a 0 works. Can you try it with one zero instead of two (i.e. `0` instead of `00`) and see if that changes things? What exactly happens when you click enter if you've entered a zero?

Just tried entering 0 instead of 00 for minutes and it indeed worked, curiously it also accepts 00 now. :S

Previously it would accept 00 (request administrator password) but the timer would not increment.

**Comment by benmobbs** [comment]
> Hi @benmobbs, thanks for the report. On my system typing a 0 works. Can you try it with one zero instead of two (i.e. `0` instead of `00`) and see if that changes things? What exactly happens when you click enter if you've entered a zero?

I think I've noticed what might have happened. The input field validates 00 to 0 now whereas when I had that issue something was preventing that from happening, so it was submitting 00 as an invalid value for 00 in your code probably, and then a failsafe for that was not incrementing the timer rather than throwing an error, or something like that.

If I type 00 now it "autocorrects" to 0 after hitting Extend or clicking out of the box (e.g. moving to the hour input) or tabbing.

No idea what's changed other than a few reboots, sorry!

**Comment by cstigler** [comment]
Hmm, got it. I'm going to close for now, but feel free to reopen if this starts causing issues again!

**Comment by ilMagnifico** [comment]
I think I have the same problem, I have just made a short video. [bug_extend_time.mov.zip](https://github.com/SelfControlApp/selfcontrol/files/4466039/bug_extend_time.mov.zip)
