### ISSUE TITLE
Doesn't block YCombinator

### ISSUE THREAD

**Issue by gohara92** [SelfControlApp/selfcontrol#607]
Hi,

Unfortunately it doesn't seem to block `https://news.ycombinator.com/`.
I've tried that URL, as well as `ycombinator.com` and `https://news.ycombinator.com/news`.

Has anyone had any success blocking this specific site?
Is there a general series of steps to take when the block doesn't work for some site?

**Comment by cstigler** [comment]
Works for me by adding `news.ycombinator.com` to my list, so maybe try that. But unfortunately networking is complicated and some things may work differently on different people's systems!

**Comment by gohara92** [comment]
Thanks, that worked perfectly!
