### ISSUE TITLE
Feature request: Block youtube.com, but not when embedded on other sites

### ISSUE THREAD

**Issue by hemdrup** [SelfControlApp/selfcontrol#610]
Hey,

Don't know if it's even possible. 

I love to just block out youtube.com as it's brain cocaine.
However, often there is an article, tutorial or a site that has a youtube link embedded, but this youtube link in the article is also blocked. 

I find that I quite often need to view these embedded links.

**Comment by charliebarber** [comment]
Hey I see you closed this, did you find a solution? thanks

**Comment by hemdrup** [comment]
No, I just saw a there have been a previous post with this topic. 
Saying it would be hard to make. Meaning, the topic has already been discussed earlier :)
