### ISSUE TITLE
Terminal CLI no longer works as documented

### ISSUE THREAD

**Issue by blackketter** [SelfControlApp/selfcontrol#615]
When I upgraded to 3.0, the instructions listed on the wiki for starting selfcontrol from the command line no longer work.  It appears that the blacklist no longer is kept in the the app defaults.

Starting selfcontrol returns this error:

`2020-05-20 07:51:56.599 org.eyebeam.SelfControl[52420:1589123] ERROR: Blocklist is empty, or there was an error transferring block information.`

**Comment by cstigler** [comment]
Thanks for the heads-up @blackketter - didn't even realize somebody had documented those in the first place.

I updated the docs in the wiki to be more accurate and comprehensive; you can check them out here: https://github.com/SelfControlApp/selfcontrol/wiki/Running-SelfControl-from-the-Terminal
