### ISSUE TITLE
Trouble blocking site with subdomain

### ISSUE THREAD

**Issue by KaighnKevlin** [SelfControlApp/selfcontrol#617]
To reproduce, add healthdata.org and covid19.healthdata.org to the blacklisted sites. Neither site is blocked.

**Comment by cstigler** [comment]
Hey @KaighnKevlin, thanks for the report. Those sites are blockable for me, so I'm guessing it's probably not a generalized issue - more likely specific to your browser or system configuration. Unfortunately, I can't troubleshoot every site-blocking issue, but I do have some suggestions for how you can troubleshoot these issues on your own:

1) Make sure you're on the newest version of SelfControl, currently 3.0 (released last week).

2) If you're using Firefox, see [our FAQ entry about disabling DNS Over HTTPS in Firefox to make blocks work better](https://github.com/SelfControlApp/selfcontrol/wiki/FAQ#q-why-isnt-my-selfcontrol-block-working-in-firefox).

3) Make sure you're not using a VPN, proxy, Tor, or similar.

4) Clear your browser cache, quit your browser, then restart it and navigate to the page again.

Hope those tips help!
