### ISSUE TITLE
Wallpaper was set to "cheater-screen" despite not cheating

### ISSUE THREAD

**Issue by s-heiden** [SelfControlApp/selfcontrol#621]
- I used a standard user account to start selfcontrol.
- As I noticed that selfcontrol is unable to lift the block after the end of the designated blocking period, I changed the user account type from standard to administrator.
- After the next login, my wallpaper was reset to "cheater-screen".

**Comment by cstigler** [comment]
Hi Stefan, that is unfortunate! Could I ask a few more questions about this one to understand a bit better?

1. What version of SelfControl are you running?

2. Has this happened once, or is it happening repeatedly?

3. How did you "notice that selfcontrol is unable to lift the block", and what happened after you changed the user account type? Did you login/logout/restart during this process?

It generally shouldn't matter whether SelfControl is started from a non-admin user account or admin, so I'm guessing there's something going on here.

**Comment by ellieb-dev** [comment]
Same problem. (I don't even think I would know how to cheat Self-Control). I'm on 3.0.1 – has happened more than once, but not every time I use SC. I've never seen "notice that selfcontrol is unable to lift the block". Thanks both.

**Comment by gcohara** [comment]
I've had this happen a few times since moving to SC 3.0.1.
It's pretty sporadic so it's hard to recreate conditions under which this occurs.

**Comment by non-cheater** [comment]
I love Self-control but this feature really sucks. 

I have never cheated, don't know how to cheat SC, but this desktop keeps coming back every few days for no reason I can understand. 

IMO it is a error to have software that WRONGLY accuses the user of cheating. 

I use my laptop for public presentations and for showing clients work.
It looks very strange. 

How do I gt rid of the screensaver and make it stay away?

Thank you

**Comment by gcohara** [comment]
You might be able to get around it by going into applications, right clicking SelfControl, clicking 'show package contents' going into /Contents/Resources/, and replacing `cheater-background.png` with an image more to your liking.

I haven't actually tried this, and I can't read Objective-C well enough to tell whether this is where SelfControl gets the background from, but I think it should work..

**Comment by cstigler** [comment]
Hey all, I hear how frustrating this is. At first it seemed like we'd solved the issue for almost everybody in the v3.0.1 fix, but it's evident that there's still a substantial number of users experiencing this problem.

It's clear that right now this feature is causing too much trouble for a small amount of benefit.

**I have disabled the tampering detection ("cheater screen") feature in the 3.0.2 build that was just released.** Please wait until your current block has finished, then upgrade your app, and it won't change your background any more.

I am finishing some stability upgrades in the next couple months that I hope will also make this feature more reliable, and I hope to turn this feature back on at that point. **If you've been experiencing this issue, I'd really appreciate your help testing an updated version when it's ready**, to make sure it's 100% fixed before I turn this back on!

**Comment by ivancarrancho** [comment]
Horrible, I share my screen in a meeting and appear this message!!!!
pleas notice me when this feature been removed to install selfcontrolapp again

**Comment by cstigler** [comment]
See my post directly above yours where I said I disabled this in version 3.0.2 (the latest release of SelfControl). Make sure you've upgraded to 3.0.2. If you upgraded mid-block, the cheater screen may show up one last time, but once you set it back to normal it won't happen anymore.

**If anyone is still having repeated issues with this in 3.0.2, let me know** so we can debug in detail. I will be shocked though, as the offending code is gone - perhaps I'll have to blame witchcraft!

One other ask for you @ivancarrancho: please consider how your tone might impact others. I hear your frustration and anger - this is an annoying issue! - but also responding to messages like yours takes a lot of energy and makes me less excited about contributing to SelfControl in the future. Let's all be kind :)

**Comment by rluedde** [comment]
@cstigler Regardless of what others may think, I am very pleased this software, so thank you for all of the time/effort that you've put into it!

**Comment by rona-gitgit** [comment]
I also appreciate this software a lot, and frequently recommend it to others. I am running version 3.0.3, and am experiencing the same problem of the "cheater-screen" wallpaper. This is an old thread, but the only one I could find about this issue. The code was apparently removed in 3.0.2., but now it seems that it's back. I wonder if I'm the only one experiencing the problem? I'm running it on a Mac using Big Sur, if that matters. Thanks in advance for any suggestions.

**Comment by cstigler** [comment]
@rona-gitgit if you manually set your wallpaper back to normal in System Preferences, does it repeatedly set itself back to the cheater screen? If so, how often? This code does not exist in 3.0.3 so I would be very surprised if it happens repeatedly
