### ISSUE TITLE
Outdated Terminology

### ISSUE THREAD

**Issue by ScottyF311** [SelfControlApp/selfcontrol#626]
May I kindly request we remove the dated (and racist) terms "blacklist" and "whitelist" from this app? Maybe to something like "Allowed" and "Blocked?"

I am not a developer but love the app, so would love any help with this minor, yet major, update.

**Comment by geoffruth** [comment]
I just created an account to post the same thing. We use SelfControl at my school, and I'm increasingly leery of deploying it to all student computers because of this racist nomenclature.

I also love the program, apart from these terms.

**Comment by cstigler** [comment]
Hi @ScottyF311 et al, thanks for the note. We're tracking this change in #624 so please head over there for updates and to share any additional thoughts.
