### ISSUE TITLE
BUG — SelfControl stuck on "Finishing"

### ISSUE THREAD

**Issue by Aarbel** [SelfControlApp/selfcontrol#628]
My SelfControl app is stuck on this. 

I can't disable it and restart it.

![image](https://user-images.githubusercontent.com/25119847/85293341-7c824a00-b49d-11ea-8c2f-f3ade3a89cfb.png)

**Comment by cstigler** [comment]
Hi @Aarbel, have you tried the fix in the FAQ?

See: https://github.com/SelfControlApp/selfcontrol/wiki/FAQ#q-selfcontrols-timer-is-at-finishing-and-i-cant-start-a-new-block-and-im-freaking-out

Wait 10 seconds, then click the button to stop block manually.
