### ISSUE TITLE
Netflix not blocked in firefox

### ISSUE THREAD

**Issue by jfedgar** [SelfControlApp/selfcontrol#630]
I added netflix.com, www.netflix.com etc to the blocklist. It is blocked in Chrome but not in Firefox (77.0.1). I tried hard refreshing, opening in a private window and starting a show and all worked fine (not a cache issue).

I am on Mac OS 10.15.5.

Self Control version 3.0.1

**Comment by jfedgar** [comment]
I was able to get around this by adding 

assets.nflxext.com
codex.nflxext.com
nflxext.com

to the block list. 

It disables the ability to actually find go to or play a show.

**Comment by cstigler** [comment]
Thanks for finding the appropriate subdomains! We'll auto-block these with Netflix in the future to improve block reliability. Fix will be in SC v4.0, coming out in a month or so.
