### ISSUE TITLE
[bypass]Change OS X time to the future to bypass selfcontrol.

### ISSUE THREAD

**Issue by John889** [SelfControlApp/selfcontrol#634]
If you change the your OS time to the future ( I changed it to 2023), Selfcontrol timer will end. A very easy way to bypass it.

**Comment by John889** [comment]
Seriously, this problem is 8 years old.

**Comment by antoineCharpentier-19** [comment]
You have cursed me with this knowledge

**Comment by John889** [comment]
@antoineCharpentier-19 
I'm reeally sorry about that man. I didn't mean that.

I now switched to pluckeye:
https://www.pluckeye.net/
and I'm using those porn lists here:
https://u.pluckeye.net/configurations/public

Please tell me if you see this comment.

**Comment by cstigler** [comment]
Reported in #28 so we'll move all discussion there :)
