### ISSUE TITLE
SelfControl timer ends early on macOS Big Sur beta

### ISSUE THREAD

**Issue by cstigler** [SelfControlApp/selfcontrol#635]
A friend reports experiencing an issue where she starts the timer for 24 hrs, it starts running normally, but then the timer ends in about 5-10 seconds and it goes back to the start screen. She's running SelfControl 3.0.2 on the macOS Big Sur beta, which I surmise could be the problem. This happens consistently and she already tried restarting her computer and app.

**Comment by Craig-Stowers** [comment]
Yes I am having the same problem as cstigler. The fans spin up while SelfControl is doing it's thing... then after 5-10 seconds the timer ends and we're back to square one. I'm running Big Sur Beta 4 (20A5343i)

**Comment by SingerCo** [comment]
Seeing the exact same error on Big Sur 11.0 Beta (20A5343j). After 10-20 seconds the timer appears to end prematurely. 

![Screen capture of issue](https://user-images.githubusercontent.com/61002377/90836279-3108e280-e30c-11ea-9b36-775d366212da.gif)

**Comment by isakic** [comment]
I managed to get it to run normally by building the app on Big Sur 11.0 Beta (20A5354i) using XCode 12 Beta 4 with Deployment Target set to 10.16. Can somebody else please try and reproduce this?

**Comment by Craig-Stowers** [comment]
> I managed to get it to run normally by building the app on Big Sur 11.0 Beta (20A5354i) using XCode 12 Beta 4 with Deployment Target set to 10.16. Can somebody else please try and reproduce this?

If this is the case... be much appreciated if someone could share the compiled app.

**Comment by isakic** [comment]
[SelfControl.app.zip](https://github.com/SelfControlApp/selfcontrol/files/5180033/SelfControl.app.zip)

If you wanna try it, here you go. 

Keep in mind that I'm making no guarantees and taking **no responsibility whatsoever** for anything that might happen if you do use this build. Hope it works for you.

**Comment by Craig-Stowers** [comment]
> [SelfControl.app.zip](https://github.com/SelfControlApp/selfcontrol/files/5180033/SelfControl.app.zip)
> 
> If you wanna try it, here you go.
> 
> Keep in mind that I'm making no guarantees and taking **no responsibility whatsoever** for anything that might happen if you do use this build. Hope it works for you.

thanks mate. of course I won't come after you if my computer implodes :D

**Comment by jazrak** [comment]
> [SelfControl.app.zip](https://github.com/SelfControlApp/selfcontrol/files/5180033/SelfControl.app.zip)
> 
> If you wanna try it, here you go.
> 
> Keep in mind that I'm making no guarantees and taking **no responsibility whatsoever** for anything that might happen if you do use this build. Hope it works for you.

Weird. This build crashes immediately upon timer start

**Comment by isakic** [comment]
As I mentioned already, you should try and build it yourself. I didn't expect the build I sent to work for anyone else.

**Comment by cstigler** [comment]
Hi all, yes I merged [this commit](https://github.com/SelfControlApp/selfcontrol/commit/bfb2bbd9a4aa4c1f16047cd4c84c1322a5ad7794) two weeks ago which fixes the main/major issue on Big Sur. That's why building it from master is working for @isakic.

I haven't fully tested the fix yet, and I've also noticed a crash immediately upon starting the block on my system (probably the same issue @jazrak noticed). That's why it's not officially released yet.

Brave souls are welcome to build the app yourselves for now (all disclaimers apply), and hopefully it works (at least well enough) for you! But for everybody else you can wait until an official release comes out, probably in the next week or two.

**Comment by Craig-Stowers** [comment]
I'll definitely donate if it starts working in Big Sur. I didn't realise how much of a life saver this app is until after it stopped working. All the other solutions are so over-baked and complex (easy to override too).

**Comment by jazrak** [comment]
Haha, same! My productivity has definitely tanked since I installed Big Sur 😉

**Comment by cstigler** [comment]
Hi all, could you please test this beta version of SelfControl (attached) to see how it works for you? In particular I'm interested in:

1. Does it work for you on Big Sur, with whatever features / functionality you usually use? Do you get any crashing (as you mentioned @jazrak) or other unusual behavior?

2. If you have access to a machine running an older OS (i.e. anything before Big Sur), does this beta version still work normally on that machine?

Let me know, thanks for the help!
[SelfControl-3.0.3-beta.app.zip](https://github.com/SelfControlApp/selfcontrol/files/5186093/SelfControl-3.0.3-beta.app.zip)

**Comment by Craig-Stowers** [comment]
ok i'll have to test it after my existing selfControl session ends. I'm currently on the version jazrak posted which crashed after starting a session but it still blocked the websites

**Comment by SingerCo** [comment]
Hi @cstigler 

I've installed and ran the beta version. At the moment the beta version has appeared to fix the issues I was seeing, it's been running for ~10 minutes, successfully blocking the sites on the blacklist, and the timer window is counting down completely fine with no crashing issues. Adding to the blocklist and extending the timer works just fine as well, not seeing anything unusual but I'll give it some more time.

Unfortunately don't have access to a machine running an older OS so this is as much as I can test, sorry!

**Comment by Craig-Stowers** [comment]
@cstigler , I'm running the latest Big Sur (20A5364e), so far your updated version has run without a hitch. I'm about 1 hour into a session with no crashes. Nothing unusual at all.

**Comment by jazrak** [comment]
@cstigler I can also confirm that there are no obvious issues with the build you linked. Timer started fine and did not stop prematurely :)

**Comment by cstigler** [comment]
Thanks y'all for testing! Sounds good so far. I'll give it a couple days for any other feedback to roll in, and will find a machine running an older OS to test on. Expect a release with the fix around the end of the week, or maybe even earlier.

**Comment by cstigler** [comment]
Version 3.0.3 just released with Big Sur compatibility! Use the "check for updates" function to upgrade, or download again from selfcontrolapp.com
