### ISSUE TITLE
Improvements: Terminology change: whitelist/blacklist --> allowlist/blocklist

### ISSUE THREAD

**Issue by papaya34** [SelfControlApp/selfcontrol#637]
There is a mistake in the patchnote: it's not an improvement, it's a regression. The definitions and origins of the words Blacklist & Whitelist have no racist connotation. Apple is not a linguistic authority. 

Furthermore, Self Control is used far beyond USA. The fact that US has major problems with racism doesn't mean that every other country has the same issues. It's annoying that US projects its own issues upon other countries.

What next? Stop using the term whitewash which was invented in the context of paint/bleach? Stop painting our doors white? Stop making black furniture? This whole thing is just absurd. What about red flags what are we going to do about that?

Why don't we just remove "Black" and "White" from the English lexicon entirely?

We use black for funerals and white for weddings. Black is a symbol of depression, fear, death. White is a symbol of purity, happiness, and hope. Eliminating words that have the word “white” or “black” in them will do nothing to change these perceptions.

It's chocking to associate Black & White to skin color. With these kind of measures, you think help doing something against racism but you're glorifying it twice more by endorsing the notions of races. Apart from an extreme minority, no one has ever associated these terms with an ethnic group.

Words only make sense in context. It is therefore futile to want to give it a meaning out of context. 
We should not dictate to people the way they speak. Otherwise we live in a dictatorship. This is sometimes the case in the USA, where there is a dictatorship of thought. Like in 1984 with the "tought crimes".

This kind of measures especially relieves the conscience of the majority. It does not change the situation of minorities.

Symbolically, having a black president for eight years has not dramatically changed racism in the United States. It is a state of mind far too ingrained to be erased by such ridiculous initiatives as removing the word "black" in negative contexts. 

What a misery to introduce such weak measures on the pretext that it is "better than nothing", the height of contemporary activism.

Companies are so afraid to appear racist, that they prefer to forget the elementary rules of “context”, a concept too complicated for activists who prefer writing history "all white all black"... oops, of course I wanted say Manichean.
McCarthyism of thought in all its splendor! All those silicon valley boys have to be seen to be doing something. Doing nothing is as good as being racist filth you know.

Are we going to start building black houses in sunny areas and removing white and black cars from the fleet?
Will there always be white hat / black hat hackers? Or approved hackers and non-approved hackers? Lots of questions this summer! This movement and awareness, action, is a good thing, but any ridiculous turns should be avoided. 

We will have to remove red, black, yellow and white... The Germans, the Belgians, the Spaniards and many others (CIO) will have to look for a new flag. Except that these colors are constructions of the mind that do not describe the reality of real skin colors.

We will end up with an Orwell Newspeak without nuance and only in political correctness imposed by a small group of extremists. 
Rewriting history like we're doing right now won't do any good, we better explain it and make sure it doesn't happen again, rather than erase everything and do like nothing had ever existed. 

It is not really to paying tribute to all those who undergo all this.
We should stop taking offense at the smallest details that we thought were shocking and we should stop split hair.

Ostracism of words is a very American phenomenon. When something bother us, we hide it, like the F-Bomb, the N-Word in order not to write it anymore. 

We have more important things to work on.
I seriously doubt any black person is offended by this. 999 times out of 1000, it is a white person who's getting offended on someone's behalf. ...advocating and arguing about change that literally no one is asking for.

There is no reason to change decade old nomenclature and spread confusion for millions because someone's, somewhere feelings are hurt over freaking trivialities. No one has ever associated those words with people.

Continuous tending towards "special snowflake sensibilities" has made the world a more and more stupid place over the last decade or so. "Political correctness" is the bane of modern society.
We need more "grow the fuck up" as far as I'm concerned (don't take this personally, I mean this in a general sense).

**Comment by cstigler** [comment]
Hi @papaya34, I hear a lot of frustration and anger, and that's OK. I empathize with some of those feelings, and acknowledge that this is a fraught and complex topic. There are intense feelings on both sides, and both sides are trying to defend something critical to them and to society (racial equity, free speech).

Two things to clarify upfront:
1. SelfControl is not an Apple product, so Apple's linguistic authority doesn't matter. The only two people involved in this decision were myself and @slambert, and I've done nearly all of the development/product work on SelfControl for the last 10 years (though I hope this'll change at some point!). Neither of us is paid for this.
2. While I'm happy to talk about the topic, the decision's made and isn't changing.

Personally (not speaking for Steve here), I also feel some frustration when I read these terms described as racist/oppressive with little justification. While some terms like "master/slave" have an obvious racially-charged background, "whitelist/blacklist" is different. It doesn't have racial origins, and it isn't used in a racially-charged manner today, so I don't see the obvious racial connection. Some people argue that the use of "white" to represent good and "black" to represent bad could have racially divergent impacts today, regardless of the intention (would love to see research on that). But it's hard to get rid of those splits entirely without eliminating the entire concept of duality, which is tied to white/black across the world (ex: yin/yang in Chinese philosophy). And I do think there's a real and significant cost to this growing pressure to conform and reshape speech.

BUT - despite that frustration, I wanted to remove those terms for a few reasons. One is that it's easy to change and the alternatives are just as clear. But the second reason, and what I think is more important, is that not changing it could create an appearance of racism that could still be concretely harmful. I'd hate for a Black user of SelfControl to see those terms and think we don't care about them, and similarly I'd hate for a white supremacist to use SelfControl and see implicit support. The most important thing to me is that we show our support for the broader social movement against racism - even if this particular change doesn't seem terribly rational to me.

That said, my logic doesn't need to constrain you! If you disagree with our choice, I encourage you to make a different terminology choice in your own software, book, sign, or anything else you create. I won't be offended, and I think it's OK for different people to make different terminology decisions. ✌️

**Comment by papaya34** [comment]
Thanks for your prompt answer. 

Has anyone asked you to cancel this  B-Word (lol) ? Has anyone ever felt offended by those terms in the first place? Did you receive complaints? My opinion is the following: if Apple did not release these guidelines, I highly doubt you would have even thought about adding these "improvements". 

Inclusive languages, newspeak, ban of so-called offensive movies from some platforms, cancel culture everywhere... It's censorship at all stages and you shouldn't be proud of yourself to bow down to this collective nonsense. 

Such changes drag down society as a whole: it weakens language, it weakens culture, it weakens critical thinking for not a single gain in value. It's an insult to those who fought for liberty in the past in arts or in battlefields.

As a (great!) software developper, you should resist these temptations to conform to this police of thought. You're free minds, you're not doomed to surrender to nonsense promoted by big corporations for chimeric reasons. 

If you feel a need to do something against racism, do something that really matters: start a politician career, start a movement, support associations related to these causes, help poor people from ethnic minorities around you, hire them... 

You and I share, I think, the same disgust for racism. And we both know it's meaningless to change 2 words in a software. I insist here: it's doing more harm than good as you contribute to associate the Black color with Skin Color... Black is an ink color, it's a suit color, it's an underwear color, it's a car color, and "blacklist" remains in the dictionary as of today ("put something on a blacklist"). You contribute to make it the new N-Word.... Sad Sad Sad!

**Comment by cstigler** [comment]
In response to the top point, I actually [changed this terminology in SelfControl](https://github.com/SelfControlApp/selfcontrol/issues/624#issuecomment-647217466) before Apple released its updated guidelines, so no - their guidelines had nothing to do with our change. This change was prompted by complaints, some of which you can read in that thread.

I don't have time to keep responding on this thread, but I'll say that I agree that changing these two words is largely inconsequential, and that we can find much more impactful ways to combat racism. For me, I try to donate to organizations like the [National Urban League](https://nul.org/donate) and the [Southern Poverty Law Center](https://donate.splcenter.org/), and used my time as a people manager to work towards recruiting/retaining diverse talent.

Although I can't respond more here, I encourage you and anybody else reading this to keep open minds and an open dialogue, and find the actions that work for you to make the world a better place :)

**Comment by papaya34** [comment]
1) In life, small renouncements beget largest. 
Soon you're gonna have to answer requests to changing the black color of the SelfControl logo. 
And other business will have to do the same one day, indirectly because of small renouncements like those acted here. 
You think it's inconsequential, but it's not at all. Butterfly effect is not a myth. 

2) Of course you don't have time to answer further due to a simple CRM rule: never answer someone more than twice on social network. I agree with this rule. So it's my final message as well. 

3) You're admitting your improvements are useless, but still want to keep them in SelfControl. 
That's either a huge cognitive dissonance here or just a wonderful example of hypocrysy. Words don't matter, only acts do, and at the end of the day you keep these changes live so you really think they are valuable despite all the factual elements I brought to this topic. 
It's not because Twitter, JPMorgan or other companies submit to stupidity, that it's the right move.

These improvements are factually racist regressions by associating generic colors with skin topics. All over google news you can find articles using "Blacklist" words. Only a sick (racist) brain could associate these words with racism and offensive language. It's seriously not flattering for those who align to this opinion. 

4) Don't worry, I will not promote this discussion anywhere. It will remain "confidential" here, I'm not a nasty activist. I'm just trying to make you think, you the individual behind this retard decision, with a broader scope about these issues. Bye.
