### ISSUE TITLE
Feature Request: Make blocks independent of the computers local record of time

### ISSUE THREAD

**Issue by FuzzyLogic123** [SelfControlApp/selfcontrol#650]
It would be good if self control had its own **internal clock running** via the internet or something to **stop me just changing the time on my computer** to get out of a block.

I just go to date and time preferences to change the time and it ends the block. Sometimes I cant help myself.

I dont know anything about programming so I dont know how feasible this is but it would sure be helpful to me

Thanks for anyway who took the time to read this.

**Comment by slambert** [comment]
Duplicate: https://github.com/SelfControlApp/selfcontrol/issues/28
