### ISSUE TITLE
You were added to Awesome Humane Tech

### ISSUE THREAD

**Issue by aschrijver** [SelfControlApp/selfcontrol#652]
This is just a FYI issue to notify that you were added to the curated awesome-humane-tech in the 'Mindfulness' category, and - if you like that - are now entitled to wear our badge:

[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)

By adding this to the README:

```markdown
[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)
```

https://github.com/humanetech-community/awesome-humane-tech

**Comment by slambert** [comment]
Aw shucks! Thanks

**Comment by cstigler** [comment]
Thank you!
