### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by theonlygusti** [SelfControlApp/selfcontrol#653]
How could I do what this app does without using it? E.g. I'd guess by tweaking macOS network settings via the Terminal.

**Comment by cstigler** [comment]
The two basic blocking mechanisms are null entries in the `/etc/hosts` file, and adding firewall rules to the `pf` built-in firewall. If you're looking for more detail, you can read the source code - BlockManager.m is a good place to start. Good luck!
