### ISSUE TITLE
Store config in home directory

### ISSUE THREAD

**Issue by jaworek** [SelfControlApp/selfcontrol#657]
Would it be possible to store config and blacklist in HOME directory?
Currently it seems that all of it is stored in programs internal database.
It would be useful for backup and sharing.

**Comment by cstigler** [comment]
We probably won't change this anytime soon, but the config is currently stored in `Library/Preferences` so should be backed up just fine by most backup programs.

If you're looking to share blocklists with your friends (or save a favorite blocklist), try using the `File --> Save Blocklist` option and you'll get a nice shareable file!

**Comment by jaworek** [comment]
I understand. Thank you for the reply.
I mainly asked about this because I backup my configs from home directory using git. 
This is quite a simple solution that does not require use of more complex software like TimeMachine.
Also any change can be easily tracked and commited, without the need from me to remember every time to export blocklist manually. Although, I guess I could make some kind of wrapper script for that or link it from `Library/Preferences`.

I'll post an update if I figure it out, for anyone else interested in something similar.

Here's an example of how it works:
https://drewdevault.com/2019/12/30/dotfiles.html
https://git.sr.ht/~sircmpwn/dotfiles/tree

**Comment by slambert** [comment]
Not sure exactly what you need, but have you checked out this?

https://github.com/lra/mackup

It supports SelfControl already.

**Comment by jaworek** [comment]
Thanks! Looks interesting. I'll check it out.
