### ISSUE TITLE
Self control stuck on finishing - again

### ISSUE THREAD

**Issue by kmh1000** [SelfControlApp/selfcontrol#658]
Sorry, I'm having the same issue as in #642 . I'm not sure what the solution was for that one, but it's closed. Previously, whenever I was having this type of problem (always after using VPN) #486 would fix the problem, bu not this time. This is annoying, but no real complaints - great program and I find it immensely useful!

**Comment by cstigler** [comment]
@kmh1000 replied to you in the other thread - hopefully you've got it worked but email me if not!
