### ISSUE TITLE
Feature Request: Have Multiple Blocklists with different Timers?

### ISSUE THREAD

**Issue by DangerDave93** [SelfControlApp/selfcontrol#659]
I've been using SelfControl to block porn sites. I've used terminal to extend the block time to months. I've amassed quite a long list of porn sites on my blocklist, to the point where searching for new ones just isn't worth it. This has really helped me with my porn addiction. 

However, I also want to use it to block normal distracting sites, such as youtube or reddit. However, I don't want to add those sites to my blocklist, because then that means no youtube or reddit at all for weeks or months. So ideally I'd have one blocklist for porn that I'd set the timer for months for, and another blocklist for normal distracting sites, that i can block for hours. Each blocklist and timer would be independent of eachother.

Is this too much to ask for you guys to code in? Are there some terminal commands that might make this work for me?

**Comment by cstigler** [comment]
Unfortunately doesn't work today and probably won't be added in the near future, but I understand the need! Two things to be aware of today that don't solve your need, but might help you get closer:

1) you can save blocklists to files / open them later (File --> Save Blocklist), to keep your two lists separate. Only one block can be running at a time, though.

2) You could use a third-party scheduling tool like [auto-selfcontrol](https://github.com/andreasgrill/auto-selfcontrol) to schedule blocks, e.g. have one run between X and Y time each day
