### ISSUE TITLE
mDNS shouldn't be blocked by allowlists

### ISSUE THREAD

**Issue by sheonhan** [SelfControlApp/selfcontrol#660]
Hi! A longtime user and big fan of SelfControl here 🙏
I've been trying to use my printer (connected via wifi) while using SelfControl but couldn't get it working.

Here are things I've tried so far. Using a network monitor ([Radio Silence](https://radiosilenceapp.com/)), I identified that three processes are used when I click print: `printtool`, `commandlnk`, `ipp`.
<img width="729" alt="Screenshot_2021-01-13_16 30 35" src="https://user-images.githubusercontent.com/4163701/104512778-b98a6700-55bc-11eb-858d-ffca97fce521.png">

And they all use only one local IP address (192.168.1.156) with port 631, which is apparently for IPP (Internet Printing Protocol). However, the printer still appears as "offline" even after allowlisting the IP address:

<img width="498" alt="Screenshot_2021-01-13_16 29 04" src="https://user-images.githubusercontent.com/4163701/104513051-0ec67880-55bd-11eb-9597-9eed05b67767.png">

Do you have any guess about what's making the printer (or some process) "think" that it's offline? I guess I can use WireShark to dig deeper, but just wanted to check before I take that (possibly long) route... Thanks!

**Comment by sheonhan** [comment]
Actually, I went ahead and did some spelunking using WireShark and found out that I also need to whitelist the IP Address where [mDNS](https://en.wikipedia.org/wiki/Multicast_DNS) query is issued. Leaving it as a screenshot (IP address to allowlist is in the red box below) here if anyone runs into this issue in the future! 
<img width="951" alt="Screenshot_2021-01-13_16 46 30" src="https://user-images.githubusercontent.com/4163701/104514532-682fa700-55bf-11eb-8d16-83cb8d900ef7.png">

**Comment by cstigler** [comment]
Good job figuring that out @sheonhan! It seems to me like we should improve this, so leaving it open as a bug.

Every allowlist already default-allows all traffic on ports 53 (DNS), 123 (NTP), and 67/68 (DHCP). I don't know much about mDNS, but it seems like it'd be reasonable to default-allow port 5353 for that also. Does that make sense to you?

**Comment by sheonhan** [comment]
Hey thanks! Ah, maybe my screenshot above is a bit misleading, but the IP address in the red box wasn't my local IP address. I tried using `dig` to find out where that led to but didn't get much clue...

**Comment by cstigler** [comment]
Hmm, I think the dest IP shouldn't matter, right? I'm assuming it was still on port 5353 (which seems to be the standard for mDNS)? My thought is that we'd just allow traffic on port 5353 regardless of where it's coming/going to...

**Comment by sheonhan** [comment]
Oh I see what you mean. Yeah, sounds right. Should it be added inside [this](https://github.com/SelfControlApp/selfcontrol/blob/8aef26354764706af70a6d7c569235e4d2a5dace/Block%20Management/PacketFilter.m#L54)? (Just a random guess since I've never worked with Objective-C... 😅 )

**Comment by cstigler** [comment]
Yep totally that's it! Basically we just need to add lines there to allow 5353 just like we do the other ports. Lemme know if you wanna PR it, otherwise I'm happy to go put it in there myself :)

**Comment by sheonhan** [comment]
Cool! I think I can give it a shot. Will follow up with a PR!

**Comment by sheonhan** [comment]
PR is here! https://github.com/SelfControlApp/selfcontrol/pull/665

**Comment by cstigler** [comment]
Closing, thanks for the fix :)
