### ISSUE TITLE
Unable to start from CL - ERROR: Could not read a valid block from file file

### ISSUE THREAD

**Issue by firvorski** [SelfControlApp/selfcontrol#663]
Hi,

I export the blocklist from the main menu using File / Save Blocklist. Then I pass the path to that file on the command line but always get this error:

> ERROR: Could not read a valid block from file
> ERROR: Block could not be read from file

The command is simply
`sudo /Applications/SelfControl.app/Contents/MacOS/org.eyebeam.SelfControl $(id -u $(whoami)) --install /Users/user/Documents/Blocklist.selfcontrol 2021-01-18T12:18:10Z`

The full error:
> 2021-01-18 11:49:03.999 org.eyebeam.SelfControl[97054:22565638] ERROR: Could not read a valid block from file file:///Users/user/Documents/Blocklist.selfcontrol
> 2021-01-18 11:49:04.001 org.eyebeam.SelfControl[97054:22565638] ERROR: Block could not be read from file /Users/user/Documents/Blocklist.selfcontrol

Is there another way to create the blocklist file in the correct format maybe?

Thank you

**Comment by cstigler** [comment]
Hi @firvorski, haven't heard of anybody having trouble with that bit before. There are two reasons that error can show:

1) the file at that path can't be read

2) it's read successfully but doesn't contain one or both of the required properties (`HostBlacklist` and `BlockAsWhitelist`)

To confirm, are you positive the file can be read at that path (i.e. if you do `sudo cat /Users/user/Documents/Blocklist.selfcontrol` it spits out the file contents)? That'd be my most likely guess. But if it's readable, that means something's wrong with the properties. I'd try saving a few times in case something strange went wrong the first time.

You could also try opening the blocklist with a plist editor to see if it's valid and if both properties are there.. that'd be my next step.

**Comment by firvorski** [comment]
Hi @cstigler 
Thank you very much for your response.
Yes, you were absolutely right the path to the file in my shell script had a typo. I only realised that after getting the same error whether the file was there or not.
Thanks again, it works perfectly now.
