### ISSUE TITLE
Block twitter, but not twitter API

### ISSUE THREAD

**Issue by maurelian** [SelfControlApp/selfcontrol#664]
Is it currently possible to block twitter.com, but allow api.twitter.com? 

The "allowlist" feature seems to be a way of restricting everything but what is on listed. 
This would require something more like a `.gitignore` style of pattern matching on different paths. 

So my block list would have: 

```
twitter.com
!api.twitter.com
```

I don't think there is anyway to achieve that right now, but please lmk if I'm missing something.

**Comment by cstigler** [comment]
Hey @maurelian, have you tried unchecking the "Block common subdomains" setting in the SC Preferences pane? (SelfControl menu --> Preferences)

I think that should do it. api.twitter.com is actually a hardcoded common subdomain for Twitter we use so the block works for most people ([see this code](https://github.com/SelfControlApp/selfcontrol/blob/8aef26354764706af70a6d7c569235e4d2a5dace/Block%20Management/BlockManager.m#L298)). But if you uncheck that preference, we won't add it to your blocklist.

Besides the "common subdomains" we block (ex: `www`), subdomains _aren't_ specifically blocked by SelfControl today, so there shouldn't be a need for an exclusion syntax. If they get blocked in other cases, it just means they share IP addresses (an unfortunate side effect of using IP-based firewall as a blocking method).

**Comment by maurelian** [comment]
Thanks @cstigler, seems I forgot to respond, but that has been working perfectly for me since you posted that. Thanks!
