### ISSUE TITLE
Make SelfControl a Universal Binary to support Apple Silicon and the M1 chip

### ISSUE THREAD

**Issue by mariobrostech** [SelfControlApp/selfcontrol#667]
Hi,

Is there any way that you can compile the next release of SelfControl as both x86_64 and arm64 to add native support for Apple Silicon Macs? If you're compiling in Xcode, it should be a simple checkbox with most things working out of the gate (though I'm not much of a dev myself, so I can't speak to any problems you may run into by doing this). A change like this would be much appreciated for those who are getting an M1 Mac because Apple will, eventually, pull the plug on Rosetta 2 since it's considered a temporary compatibility mode for existing, legacy programs.

I hope you take this request into consideration, and thanks for making SelfControl such a great app that so many people can rely on!

**Comment by cstigler** [comment]
Hi @mariobrostech, thanks for the suggestion. Yes, this is already done on `master` and will be in the upcoming 4.0 update!
