### ISSUE TITLE
Question: Permanent block

### ISSUE THREAD

**Issue by rossoneris** [SelfControlApp/selfcontrol#671]
Can this app be used for blocking specific websites for users permanently instead of just daily ?

**Comment by imflash217** [comment]
This is currently not available but you can still achieve it in a way-around:
I think we can add a really big hours to block it indefinitely. Lets say add 2400 hrs (this will block for 100 days straight)
NOTE: Be aware that if you started the timer for say 2400hrs to block a specific website then after some time if you added another website to the blacklist, then it will be blocked for so many hours (~100 days) and it cannot be stopped till the timer runs out. So, be careful and decide cleverly before you do so.

Hope it helps.
