### ISSUE TITLE
No longer blocking some websites after upgrading Mac OS

### ISSUE THREAD

**Issue by hlkong** [SelfControlApp/selfcontrol#673]
Recently I upgraded my Mac to V11.2.3 and SelfControl began to no longer be able to block some websites I added to the block list, using Firefox, e.g., facebook, twitter, etc. I tried re-installing but it didn't help. Hope the issue get resolved! Thanks!

**Comment by cstigler** [comment]
Hi @hlkong, if you're using Firefox the issue is probably related to DNS Over HTTPs (DoH), which is now enabled by default in Firefox. If you restart Firefox after starting your block, it should work properly.
