### ISSUE TITLE
How to completely remove SelfControl App from my Mac?

### ISSUE THREAD

**Issue by auxiliaryjoel** [SelfControlApp/selfcontrol#679]
I set the wrong start time initially. I need access to Facebook out of work hours in order to work my 2nd job as a Band Manager (lots of Facebook promotion and event creations) but during work hours I want Facebook blocked.
I set the wrong start time initially and now I need to change it. But that does not seem possible,
Therefore this app is unusable for me, and I want all traces of it removed from my iMac.
How do I change the start time?
Can someone give me step by step instructions on how to completely remove this app from my mac, including any settings it may have adjusted?

**Comment by cstigler** [comment]
Hi @auxiliaryjoel, when you say "set the wrong start time", do you mean the wrong block duration / end time? SelfControl doesn't have built-in block scheduling, so If you're using a third-party scheduling tool like auto-selfcontrol, that's a different deal.

If you set the wrong block duration (i.e. longer than you wanted), the best thing to do is wait for the timer to run out. SelfControl limits block durations to 24 hours so it shouldn't take longer than that.

If you ended up with an extremely long block (e.g. you followed some instructions on the internet to make your block extra-long) and you can't wait for it to run out, you can email me at charlie+sc679@charliestigler.com with details of exactly what happened and I can help you out.
