### ISSUE TITLE
Implementation 

### ISSUE THREAD

**Issue by MatteoVannucchi** [SelfControlApp/selfcontrol#697]
Hi!

I noticed that if I open my Mac's settings and manually change the time so that it goes past the chunk of time I set with SelfControl, the timer expires.
Is there something you could do not to let this "trick" work?
Apart from this little flaw, it's a terrific app, and my productivity spiked since I began using it.
Thanks!

**Comment by cstigler** [comment]
Thanks folks - this was reported long in #28 so closing to move all discussion there :)

@jenspots yeah, that idea has come up a few times and it is definitely possible but it sounds like a loooooot of work to get it reliable in the edge cases (power outages, crashes, network problems, etc). Hence it has not happened yet. Contributions always welcome!
