### ISSUE TITLE
Users can disable SelfControl by changing the time

### ISSUE THREAD

**Issue by Bella-steven** [SelfControlApp/selfcontrol#699]
So, recently I found out that by changing the time/clock, the app would disable the SelfControl 

SelfControl version? 3.0.3
macOS version? 11.2.3
I do not use any VPN or proxy.

So for example I set a blocker for 3 hours at 8 am, but without waiting, I could just bypass it by open the system preferences, click "date and time", then unlock it and change the time to 12 pm, then boom, you could disable the block. 

I hope this issue could be fixed since it's such a perfect app, but with this bug, I just thought it's meaningless to use this app anymore, as you could bypass it that easily. 

It would be great if this problem could be fixed asap, thank you.

**Comment by cstigler** [comment]
Hi @Bella-steven , yes unfortunately this is true! There's discussion of this issue already in #28, so I'll close this to centralize all discussion there. It'd be awesome to improve this at some point, but I wouldn't hold your breath waiting for a fix :)
