### ISSUE TITLE
Would it be possible to enable subdomains?

### ISSUE THREAD

**Issue by avatar-lavventura** [SelfControlApp/selfcontrol#702]
**Is your feature request related to a problem? Please describe.**

I want to block: all sites under `https://www.binance.com/en/futures/`, but I do not want block `https://www.binance.com/en/trade/`

When I add `https://www.binance.com/en/futures/` into the blocklist its converted into: ```binance.com```, and selfcontrol blocks all the `binance` domain.

Would it be possible to have whitelist for subdomains?

Example:
I want to block subdomain of stackexchange, ex: https://physics.stackexchange.com/ , but when I do that, it also blocks https://stackoverflow.com , which I don't want.

**Comment by hhsue** [comment]
Interesting behavior. Are these real examples by any chance?

**Comment by avatar-lavventura** [comment]
@hhsue Yes sir I was having this issue for a long time. For example, I want to block https://www.binance.com/en/futures/ but instead it block complete binance domain.
