### ISSUE TITLE
Code-signature changed warning 

### ISSUE THREAD

**Issue by suschizu** [SelfControlApp/selfcontrol#721]
Hello @cstigler,
I've received a code signature change warning while installing selfcontrol.app.
Can you verify that your code signature for 'Charles Stigler' has changed?
Thank you!

**Comment by cstigler** [comment]
@suschizu yes, this is correct - the Developer ID used to sign SelfControl changed in 4.0

What kind of warning did you receive? Do you have a screenshot? I wasn't expecting the switch to trigger any warnings for our users, so hoping this isn't a common occurrence!

**Comment by suschizu** [comment]
@cstigler - great thanks for the answer - good to hear that everything's fine 👍 
… Nono - it's not a bug - sorry for the imprecise statement - it's just a self made program that warns me if a code signature changes - for security reasons :)

**Comment by HLFH** [comment]
<img width="731" alt="Screenshot 2021-10-28 at 21 12 27" src="https://user-images.githubusercontent.com/2359059/139328556-e8e93027-bdf7-42f3-8b50-38ae8c882d77.png">

I think that's the screenshot.
