### ISSUE TITLE
Selfcontrol changes /usr/local/etc/ permissions (breaking homebrew)

### ISSUE THREAD

**Issue by karbassi** [SelfControlApp/selfcontrol#727]
# Summary

While SelfControl is running (blocking), the permission of `/usr/local/etc/` is changed.

# Background Info

SelfControl version: `Version 4.0.1 (408)`
macOS version: `11.6`
Do you use a VPN/proxy, and if so which one: **No**
Has this _ever_ worked for you on a prior version of SelfControl? If so, when? **3.x worked, I believe**
Any other special system setup we should know about?

# How Do We Reproduce This Issue?

1. Check permissions of `/usr/local/etc/` before installing/using SelfControl. `sudo chown -R $(whoami) /usr/local/etc`
2. Start SelfControl blocking
3. Observe permission change of `/usr/local/etc/`.

# What _Should_ Have Happened?

SelfControl shouldn't change `/usr/local/etc/` permissions.

# What Actually Happened Instead?

See above.

**Comment by cstigler** [comment]
Oh, goddamnit. :( Thanks @karbassi for raising this.

Why this happens: users have occasional permissions issues with all system directories (i.e. something's wrong with their perms and we can't write to X directory) which causes awful bugs, so SC has always tried to fix permissions on the directories it writes to as a way of reducing issues. In SC 4.0 we moved our critical settings file to `/usr/local/etc`, which is a directory that doesn't exist on stock OS X systems but used by some other software, including Homebrew. SC4.0 will create that directory if it doesn't exist (which I think it won't for most users), and the goal of the `chown`/`chmod` here was just to fix perms back up to "normal". Which apparently isn't the "normal" that Homebrew wants.

Would you be able to share with me what the default perms are on `/usr/local/etc` with a Homebrew install? As in, what did it look like when Homebrew was installed without SC?

The options are basically: change our permissioning to play nice with Homebrew, OR move our file somewhere else (but that's a whole migration hassle). Really hoping we make it work with the existing file location...

**Comment by cstigler** [comment]
@karbassi I hear that - unfortunately I'm not sure about a workaround. But I thought a little more on it and think there's an easy fix given homebrew's preferred permissions: we can just leave the owner as-is while keeping our `chmod`, which should ensure it's still readable by everybody (which is what we really care about).

I put this fix in and it appears to be working for me. Could you try [this version of SelfControl I just built](https://github.com/SelfControlApp/selfcontrol/files/7394391/SelfControl.4.0.2.beta.app.zip) and see if it's also working well for you with Homebrew? Just quit SC once your current block finishes, replace with this copy, and start another block.

If so I'll release as 4.0.2 to fix for everybody!

**Comment by karbassi** [comment]
@cstigler tested and it works!

As a side note, it would be amazing to use the Touch ID rather than only password verify.

**Comment by cstigler** [comment]
Great, thanks for testing - just released as 4.0.2.

Touch ID has been a feature request for a while, but I don't believe it's possible with Apple's APIs unfortunately. See [this thread](https://developer.apple.com/forums/thread/106386?answerId=323327022#323327022) for reference. If it were possible, would definitely want to add it!
