### ISSUE TITLE
Block all websites in a text file in a single go

### ISSUE THREAD

**Issue by imflash217** [SelfControlApp/selfcontrol#749]
**Is your feature request related to a problem? Please describe.**
It is very tiresome to add each website url individually to block it. I have a long list of 1000s of urls that I need to block for my institution

**Describe the solution you'd like**
It would be extremely helpful to upload a text file containing the list of urls to block.

**Describe alternatives you've considered**
I have tried to include multiple website (separated by comma `,`) in the `Host` placeholder in UI. But, its not working.

**Comment by cstigler** [comment]
Hi @imflash217 , responded to your comment but you can already do this, just need it to be newline-separated and then copy/paste
