### ISSUE TITLE
Since starting use of SelfControl recently, Mail app is no longer loading content 

### ISSUE THREAD

**Issue by declancooper** [SelfControlApp/selfcontrol#775]
I hadn't been using SelfControl for a while, just started using it again recently and ever since I have, at the top of any emails with remote content to be loaded I get a message at the top stating "Your network preferences prevent content from loading privately" and I have to click a box 'Load Content Directly' to do so. This issue occurs even when SelfControl is not actively blocking, or even open.

Does anyone know how to change it back so Mail automatically opens content? And how to keep SelfControl from blocking it again afterwards? (assuming SelfControl is the culprit - but I can't think of any other changes that would be responsible).

Thanks for your help!

**Comment by fahrenfort** [comment]
This issue has nothing to do with SelfControl. It is a feature that is on by default in macOS Monterey. You can change this behavior by going into Mail > Preferences > Privacy tab, and then uncheck "Protect Mail Activity". After that, behavior of your mail app goes back to previous behavior.

**Comment by declancooper** [comment]
Thank you very much for clearing that up and providing the fix!
