### ISSUE TITLE
"Show countdown in Dock" isn't working.

### ISSUE THREAD

**Issue by joranv1** [SelfControlApp/selfcontrol#777]
# Summary

In the settings of the app, there's an option called "Show countdown in Dock". However, it's not working for me.
I have it enabled but I don't see any countdown in the dock.

# Background Info

SelfControl version -> 4.0.2 (410)
macOS version -> macOS 12.2 Monterey
Do you use a VPN/proxy, and if so which one -> No
Has this _ever_ worked for you on a prior version of SelfControl -> No
Any other special system setup we should know about -> No

# How Do We Reproduce This Issue?

Enable the feature and look at the dock. There's no countdown in the dock.

# What _Should_ Have Happened?

It should've shown the countdown in the dock when enabled.

# What Actually Happened Instead?

The countdown is nowhere to be seen in the dock unless the description of the feature is not clear and I'm looking at the wrong place.

**Comment by wenman-ualberta** [comment]
#### Do you currently have notifications allowed for Self Control?

- macOS Monterey Version 12.3.1.
- Self Control Version 4.0.2 (410)

I do _not_ have this issue, but was able to replicate it.

`System Preferences > Notifications and Focus > Self Control`

![image](https://user-images.githubusercontent.com/102183346/161697040-bd545bbc-5a1e-4696-b061-eb9adf8a09ed.png)

If `Allow Notifications` for Self Control is disabled, the dock countdown timer will disappear.
If `Allow Notifications` is enabled, the countdown timer will reappear.

Does this solve your issue?

**Comment by georgedonnelly** [comment]
Just tried this with SelfControl Version 4.0.2 (410) and it indeed solved the issue. Thank you!

**Comment by joranv1** [comment]
This also fixed the issue for me :)
