### ISSUE TITLE
I can open blocked sites on Google Chrome using VPN-free.pro - Free Unlimited VPN

### ISSUE THREAD

**Issue by avatar-lavventura** [SelfControlApp/selfcontrol#788]
# Summary

I was able to open the blocked sites. In `Google Chrome` (`Version 99.0.4844.83 (Official Build) (x86_64)`) I opened a new user account and installed following extension: https://chrome.google.com/webstore/detail/vpn-freepro-free-unlimite/bibjcjfmgapbfoljiojpipaooddpkpai than I was able to open all the blocked sites. Where they don't open in `Brave` `Safari` or` Opera`

# Background Info

SelfControl version? 
macOS Monterery? `12.3.1 (21E258)`

Do you use a VPN/proxy, and if so which one? 
Yes [`VPN-free.pro - Free Unlimited VPN`](https://chrome.google.com/webstore/detail/vpn-freepro-free-unlimite/bibjcjfmgapbfoljiojpipaooddpkpai) on Google Chrome.

**Comment by sporkman** [comment]
I'm not sure if this is spam or a serious question, but if it is a serious question, see the FAQ entry "Is SelfControl compatible with VPNs?" here:

https://github.com/SelfControlApp/selfcontrol/wiki/FAQ

**Comment by avatar-lavventura** [comment]
No it is not a spam, it was just a honest serious question. 

- https://getcoldturkey.com is able to manage to block even vpn is on. That's why I just want to be double sure why it is not technically possible.
