### ISSUE TITLE
How can I set block timer to infinity?

### ISSUE THREAD

**Issue by avatar-lavventura** [SelfControlApp/selfcontrol#805]
I was wondering is it possible to set block timer to a infinity number or something like 10 years?

**Comment by MrLock9** [comment]
https://github.com/SelfControlApp/selfcontrol/wiki/FAQ#q-is-there-a-way-to-start-blocks-for-longer-than-24-hours

**Comment by avatar-lavventura** [comment]
@MrLock9 I can just use https://chrome.google.com/webstore/detail/vpn-freepro-free-unlimite/bibjcjfmgapbfoljiojpipaooddpkpai to bypass the blocked blocked website, there is no need to wait 23 days response.
