### ISSUE TITLE
Blocking specific urls instead of the entire site? ex. subreddit instead of all of reddit

### ISSUE THREAD

**Issue by clee14314** [SelfControlApp/selfcontrol#812]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by clee14314** [comment]
Was looking to block certain subreddits without blocking the entirety of Reddit itself. Thank you!!!

**Comment by ramyzhang** [comment]
+1, there were past issues discussing this but they were all closed so I figure maybe this is an error that has resurfaced with a newer version. I'm using 4.0.2 on an M2 Macbook Pro

**Comment by skylarreynolds** [comment]
This would be insanely clutch and perfect

**Comment by slambert** [comment]
Dupes of:
https://github.com/SelfControlApp/selfcontrol/issues/45
https://github.com/SelfControlApp/selfcontrol/issues/185
https://github.com/SelfControlApp/selfcontrol/issues/504

See https://github.com/SelfControlApp/selfcontrol/issues/7 for more details.

Short answer is we don't have a plan for this right now, but [see our FAQ under "Q: Can you add ________ feature that is really important to me?"](https://github.com/SelfControlApp/selfcontrol/wiki/FAQ#q-can-you-add-________-feature-that-is-really-important-to-me) - particularly the part about doing it yourself or hiring someone to. Thanks!
