### ISSUE TITLE
'XPMArguments.h' file not found

### ISSUE THREAD

**Issue by Jack-Adam-Mwanzo** [SelfControlApp/selfcontrol#817]
Both version 4.0 and 4.0.2 when I run the SelfControl on xcode, kindly help me out
<img width="260" alt="Screenshot 2023-02-16 at 14 30 26" src="https://user-images.githubusercontent.com/65719477/219353360-1685a857-88e5-4001-a26e-dcbaf374583c.png">

**Comment by cstigler** [comment]
Sounds like you maybe didn't pull in the git submodules - ArgumentParser is included as a submodule.

`git submodule update --init`

**Comment by Jack-Adam-Mwanzo** [comment]
Thanks a lot @cstigler am really greatful for your help....It worked great👍🏿😁
