### ISSUE TITLE
SelfControl app causes other websites not to work properly

### ISSUE THREAD

**Issue by TronYY** [SelfControlApp/selfcontrol#820]
![](https://s2.loli.net/2023/02/28/ktQhDwYTKsEdqo5.png)
This is my blocklist, but why websites of zhihu.com can't be opened normally ？
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/24478375/221744115-6b60cf45-1106-4628-a113-def066f9fd55.png">

**Comment by cstigler** [comment]
Hi @TronYY , sorry this isn't working right for you! Unfortunately, lots of websites share servers, so blocking one can sometimes have effects on another. Unfortunately, I don't have time to debug these issues one by one, but if you want to log this as a data point for the future, please do so on issue #681. Thanks!
