### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mazinmuhammed00** [SelfControlApp/selfcontrol#821]
Site / Host Name (exactly as added to your list):https://freemovieswatch.tv

Have you followed all of the above debugging steps before adding this site? (Yes/No):Yes

Are you using a blocklist or allowlist (fka whitelist) block?: Yes

If you're using an allowlist, what other websites are on your allowlist?

How long have you noticed this issue?: 3 days

Any other notes, ideas, or comments? No

**Comment by cstigler** [comment]
Hi, sorry it isn't working right for you in this case! For sites that are incorrectly blocked, we're tracking them in issue #680. Unfortunately, I don't have time to debug these one by one.
