### ISSUE TITLE
Hi, sorry it isn't working right for you in this case! For sites that are incorrectly blocked, we're tracking them in issue #680. Unfortunately, I don't have time to debug these one by one.

### ISSUE THREAD

**Issue by mazinmuhammed00** [SelfControlApp/selfcontrol#823]
Hi, sorry it isn't working right for you in this case! For sites that are incorrectly blocked, we're tracking them in issue #680. Unfortunately, I don't have time to debug these one by one.

_Originally posted by @cstigler in https://github.com/SelfControlApp/selfcontrol/issues/821#issuecomment-1450780224_
            

issue still not resolved

**Comment by cstigler** [comment]
Hi @mazinmuhammed00, sorry it's not working for you still! We aren't tracking these as issues on GitHub, unfortunately, but I hope the troubleshooting tips in our Wiki help and you're able to figure it out.
