### ISSUE TITLE
Can force timer to end via clock in system settings

### ISSUE THREAD

**Issue by adiram359** [SelfControlApp/selfcontrol#839]
# Summary
You can prematurely cause the timer to end by manually advancing your system clock via system settings.

# Background Info

SelfControl version? 
macOS 10.15.7 

Do you use a VPN/proxy, and if so which one? 
Has this _ever_ worked for you on a prior version of SelfControl? If so, when?
Any other special system setup we should know about?

# How Do We Reproduce This Issue?
Set the timer for X hours and start the timer. Go to System Preferences > Date and Time > *hit the lock to make changes* > uncheck the box that says "Set date and time automatically" > advance the time by X hours.

**Comment by slambert** [comment]
Duplicate: https://github.com/SelfControlApp/selfcontrol/issues/28
