### ISSUE TITLE
Prevent disabling by changing date and time

### ISSUE THREAD

**Issue by gob35** [SelfControlApp/selfcontrol#843]
I'm sure lots of people here already know about this. There might be a few open issues addressing this. I still wanted to share in case I had a slightly different perspective and recommendations. 

I can easily disable a block by going to settings, turning off automatic time and date, and selecting a date in the future where the block would be finished (maybe you don't don't have to do the last step exactly like that). 

Just like many people here, I have very unreliable impulse control, so this app has been very helpful. However, it has been useless ever since I discovered this workaround.

A couple ideas:
Would it be possible for the timer in the app to be independent from time and date settings? Or maybe block those settings? Or are both of those ideas impossible? I would love to know!

**Comment by slambert** [comment]
Duplicate: https://github.com/SelfControlApp/selfcontrol/issues/28
