### ISSUE TITLE
Build for Debian/Linux

### ISSUE THREAD

**Issue by ScreamingPigeon** [SelfControlApp/selfcontrol#854]
**Is your feature request related to a problem? Please describe.**
Are there any plans to make a version for linux systems? Seems like a super cool thing to do

**Describe the solution you'd like**
I wouldn't mind getting started on writing a version of the application for Linux. If someone could point me to the docs for the core features I can get started on a barebones CLI version for debian systems

**Comment by slambert** [comment]
Hi - Someone did this years ago. 

https://github.com/SelfControlApp/selfcontrol/wiki/FAQ#q-are-you-planning-on-making-a-windows-linux-or-ios-version

You could fork ours or these:
[Self Restraint](https://github.com/ParkerK/selfrestraint/)
[Chomper](https://github.com/aniketpanjwani/chomper) 

Let us know how it goes!

**Comment by slambert** [comment]
Closing, as this would be a separate project

**Comment by ScreamingPigeon** [comment]
Thanks for the info!
