### ISSUE TITLE
Growl notifications when Self Control Period ends

### ISSUE THREAD

**Issue by kfdm** [SelfControlApp/selfcontrol#9]
http://growl.info/about.php

I 'think' it should be an easy thing to add though I am unfamiliar with objC code. My thought is that you would only need to implement the bit that fires the message when the self control period ends.

You probably would not even need to add a checkbox to the preferences if you didn't want to, since you could disable the notifications from the Growl panel
http://growl.info/images/PreferencesWindow.png

http://growl.info/documentation/developer/introduction.php

**Comment by cstigler** [comment]
We have native notifications now in the upcoming 4.0 release coming out ina  few weeks :) they only work when the app is open for technical reasons, but still something
