### ISSUE TITLE
1.5 lets me access blocked sites after I awake computer

### ISSUE THREAD

**Issue by generationfourth** [SelfControlApp/selfcontrol#95]
Hi, First off I love the app... it's been incredibly helpful, and the latest version (1.50) works smoother than ever. Except it seems like it will let me access blocked sites after my macbook pro running 10.8.2 goes to sleep and I wake it. It's all sites on my block list that work (fb, reddit, etc...). It's not every single time, it's just every so often.

**Comment by slambert** [comment]
Upgrade to the latest version. Reopen this issue if it's still a problem.
